src/main/java/uk/gov/hmcts/sscs/service/json/CcdCaseDeserializer.java, src/main/java/uk/gov/hmcts/sscs/service/xml/CustomDateTimeXmlAdapter.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Address.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Appeal.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Appellant.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Appointee.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Benefit.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/CcdCase.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Hearing.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Name.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Representative.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/TribunalType.java, src/test/java/uk/gov/hmcts/sscs/service/json/CcdCaseDeserializerTest.java, src/test/java/uk/gov/hmcts/sscs/service/xml/XmlUtilTest.java
- Created a Deserializer to convert SYA Json to a CCD Case object
- Front end still in development so made assumptions on some field names and some are missing. These are marked with TODOs
- Added Equals and Hashcode methods for the POJOs
=> SSCS-2244 Convert SYA Json to Case

src/main/java/uk/gov/hmcts/sscs/service/json/CcdCaseSerializer.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Address.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Appeal.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/CcdCase.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Event.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Hearing.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Name.java, src/main/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/Status.java, src/test/java/uk/gov/hmcts/sscs/service/json/CcdCaseSerializerTest.java, src/test/java/uk/gov/hmcts/sscs/tribunals/domain/corecase/NameTest.java
- Create a serializer which takes a CCD case object and converts into JSON ready for TYA
- Created an event domain object which records each event for a case
- If a field is not populated on an event then it is ommitted from the JSON created
=> SSCS-2245 Track your appeal JSON from CCD case

src/main/java/uk/gov/hmcts/sscs/service/MessageAuthenticationService.java, src/main/resources/config/application.properties
Missing string value for mac token secret value.
=> 2604 [AS] - Add property for mac token secret value.

src/test/resources/json/sya.json
* Updated the JSON so it's inline with what the UI generates.
=> Updated SYA JSON

build.gradle, src/main/resources/config/application.properties
Implement logging in app insights on tribunals api
https://tools.hmcts.net/jira/browse/SSCS-2690
=> SSCS-2690[SA]:Implement logging in app insights on tribunals api

src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/TyaEndpointsIt.java, src/main/java/uk/gov/hmcts/sscs/controller/ManageSubscriptionController.java, src/main/java/uk/gov/hmcts/sscs/service/MessageAuthenticationService.java, src/test/java/uk/gov/hmcts/sscs/controller/ManageSubscriptionControllerTest.java, src/test/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceTest.java
Validate MAC token sent from TYA Frontend
https://tools.hmcts.net/jira/browse/SSCS-2786
=> SSCS-2786[SA]: validate mac token received from TYA frontend

src/IntegrationTests/resources/json/appeal.json, src/main/java/uk/gov/hmcts/sscs/builder/TrackYourAppealJsonBuilder.java, src/test/resources/tya/adjourned.json, src/test/resources/tya/adjournedCcd.json, src/test/resources/tya/appealReceived.json, src/test/resources/tya/appealReceivedCcd.json, src/test/resources/tya/closed.json, src/test/resources/tya/closedCcd.json, src/test/resources/tya/dormant.json, src/test/resources/tya/dormantCcd.json, src/test/resources/tya/dwpRespond.json, src/test/resources/tya/dwpRespondCcd.json, src/test/resources/tya/dwpRespondOverdue.json, src/test/resources/tya/dwpRespondOverdueCcd.json, src/test/resources/tya/hearing.json, src/test/resources/tya/hearingBooked.json, src/test/resources/tya/hearingBookedCcd.json, src/test/resources/tya/hearingCcd.json, src/test/resources/tya/newHearingBooked.json, src/test/resources/tya/newHearingBookedCcd.json, src/test/resources/tya/pastHearingBooked.json, src/test/resources/tya/pastHearingBookedCcd.json, src/test/resources/tya/postponed.json, src/test/resources/tya/postponedCcd.json, src/test/resources/tya/withdrawn.json, src/test/resources/tya/withdrawnCcd.json
add appealNumber in tya json and minor changes.
=> SSCS-2810[SA]: add appealNumber in tya json from subscriptions

src/main/java/uk/gov/hmcts/sscs/builder/TrackYourAppealJsonBuilder.java, src/main/java/uk/gov/hmcts/sscs/domain/corecase/EventType.java, src/test/resources/tya/adjournedCcd.json, src/test/resources/tya/closedCcd.json, src/test/resources/tya/dormantCcd.json, src/test/resources/tya/dwpRespondCcd.json, src/test/resources/tya/dwpRespondOverdueCcd.json, src/test/resources/tya/hearingBookedCcd.json, src/test/resources/tya/hearingCcd.json, src/test/resources/tya/newHearingBookedCcd.json, src/test/resources/tya/postponedCcd.json, src/test/resources/tya/withdrawnCcd.json
map the ccd eventType to tya eventType
https://tools.hmcts.net/jira/browse/SSCS-2849
=> SSCS-2849[SA]:map the ccd eventType to tya eventType

src/main/java/uk/gov/hmcts/sscs/builder/TrackYourAppealJsonBuilder.java, src/main/java/uk/gov/hmcts/sscs/model/ccd/HearingDetails.java, src/test/resources/tya/adjournedCcd.json, src/test/resources/tya/hearing.json, src/test/resources/tya/hearingBookedCcd.json, src/test/resources/tya/hearingCcd.json, src/test/resources/tya/lapsedRevisedCcd.json, src/test/resources/tya/newHearingBookedCcd.json, src/test/resources/tya/postponedCcd.json
TYA: Get the hearing details based on the event date
https://tools.hmcts.net/jira/browse/SSCS-2847
=> SSCS-2847[SA]:get hearing details based on the event date match

src/main/java/uk/gov/hmcts/sscs/builder/TrackYourAppealJsonBuilder.java, src/test/resources/tya/hearingCcd.json
Get the first hearing details if eventdate not available in the hearingDetails.
=> get the first hearing details if eventdate not available

src/main/java/uk/gov/hmcts/sscs/controller/RootController.java, src/test/java/uk/gov/hmcts/sscs/controller/RootControllerTest.java
- Return 200 when azure application hits the / endpoint every few seconds polluting the logs
=> SSCS-2899 Add Root Controller

src/e2e/java/uk/gov/hmcts/sscs/smoke/GetSavedCase.java
by following revised smoke test definition
=> make smoke test independent

src/main/java/uk/gov/hmcts/sscs/builder/TrackYourAppealJsonBuilder.java, src/test/resources/tya/appealReceived.json, src/test/resources/tya/appealReceivedCcd.json, src/test/resources/tya/dwpRespond.json, src/test/resources/tya/dwpRespondCcd.json, src/test/resources/tya/hearingBooked.json, src/test/resources/tya/hearingBookedCcd.json
create evidenceResponse events in TCA.
https://tools.hmcts.net/jira/browse/SSCS-2933
=> create evidencereponse events in tca

src/test/resources/json/sya.json
- Add new fields `interpreterLanguageType `, `signLanguageType`
- Rename option `disabledAccess` to `accessibleHearingRoom`
- Add additional option `other`
=> Update JSON for SYA Hearing arrangements

src/e2e/java/uk/gov/hmcts/sscs/ccd/CreateCaseInCcdTest.java, src/e2e/java/uk/gov/hmcts/sscs/ccd/UpdateCaseInCcdTest.java, src/main/java/uk/gov/hmcts/sscs/controller/ReminderController.java, src/main/java/uk/gov/hmcts/sscs/model/reminder/ReminderResponse.java, src/main/java/uk/gov/hmcts/sscs/service/CcdService.java, src/main/java/uk/gov/hmcts/sscs/service/ccd/ReadCoreCaseDataService.java, src/test/java/uk/gov/hmcts/sscs/controller/ReminderControllerTest.java, src/test/java/uk/gov/hmcts/sscs/service/CcdServiceTest.java, src/test/java/uk/gov/hmcts/sscs/service/ccd/ReadCoreCaseDataServiceTest.java
- Create endpoint for reminders
- Send reminder to CCD as an event
=> SSCS-2926 Send reminder event to CCD

src/IntegrationTests/java/uk/gov/hmcts/sscs/sya/SyaEndpointsIt.java, src/main/java/uk/gov/hmcts/sscs/model/pdf/PdfWrapper.java, src/main/java/uk/gov/hmcts/sscs/service/SubmitAppealService.java, src/main/resources/templates/appellant_appeal_template.html, src/test/java/uk/gov/hmcts/sscs/service/SubmitAppealServiceTest.java
- Add the CCD case ID to the PDF as Appeal Reference
=> SSCS-3106 Case ID PDF

src/test/resources/tya/dormant.json, src/test/resources/tya/dormantCcd.json
https://tools.hmcts.net/jira/browse/SSCS-3238
=> Fix the junit for dormant test

build.gradle, infrastructure/main.tf
See: https://github.com/jitpack/jitpack.io/issues/1939
=> JitPack repo should be last resort

src/main/java/uk/gov/hmcts/sscs/domain/wrapper/SyaRepresentative.java, src/main/java/uk/gov/hmcts/sscs/json/RoboticsJsonMapper.java, src/main/java/uk/gov/hmcts/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/sscs/json/RoboticsJsonMapperTest.java, src/test/resources/json/sya.json, src/test/resources/sya/allDetails.json, src/test/resources/sya/allDetailsCcd.json, src/test/resources/sya/appealWithEvidenceDocuments.json, src/test/resources/sya/appealWithEvidenceDocumentsCcd.json, src/test/resources/sya/appellantPhoneNumberWithoutSpacesCcd.json, src/test/resources/sya/appellantPhoneNumbersWithSpaces.json, src/test/resources/sya/hearingWithSupportWithoutScheduleHearing.json, src/test/resources/sya/hearingWithSupportWithoutScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportAndScheduleHearing.json, src/test/resources/sya/hearingWithoutSupportAndScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportWithScheduleHearing.json, src/test/resources/sya/hearingWithoutSupportWithScheduleHearingCcd.json, src/test/resources/sya/withoutEmailNotification.json, src/test/resources/sya/withoutEmailNotificationCcd.json, src/test/resources/sya/withoutHearing.json, src/test/resources/sya/withoutHearingCcd.json, src/test/resources/sya/withoutNotification.json, src/test/resources/sya/withoutNotificationCcd.json, src/test/resources/sya/withoutSmsNotification.json, src/test/resources/sya/withoutSmsNotificationCcd.json
https://tools.hmcts.net/jira/browse/SSCS-3451
- Title added to representative
- Default title to s/m when missing for robotics
- Default first and last names to full stops when missing for robotics
=> SSCS-3451 Add title to representive for Robotics

src/test/java/uk/gov/hmcts/sscs/service/CcdServiceTest.java, src/test/java/uk/gov/hmcts/sscs/service/ccd/CaseDataUtils.java, src/test/resources/json/CaseDataContent.json
This should resolve the exceptions seen in End to End tests in the notification service
=> Use a real benefit type for e2e test

src/main/java/uk/gov/hmcts/sscs/json/RoboticsJsonMapper.java, src/main/resources/schema/sscs-robotics.json, src/test/java/uk/gov/hmcts/sscs/json/RoboticsJsonMapperTest.java, src/test/java/uk/gov/hmcts/sscs/schema/RoboticsSchemaTest.java
- Add Lanaguage interpreter type to robotics when field is set to true
- Add Sign language interpreter type to robotics when field is set to true
=> SSCS-3639 and 3646 Language interpreter robotics

src/main/java/uk/gov/hmcts/sscs/json/RoboticsJsonMapper.java, src/test/java/uk/gov/hmcts/sscs/json/RoboticsJsonMapperTest.java, src/test/resources/json/sya.json
=> SSCS-3421 Pass the PIP office number from the appeal to robotics if it

src/main/java/uk/gov/hmcts/sscs/service/AirLookupService.java
- Only load in rows with lookup_id equal to 1
=> SSCS-3696 Fix airlookup exception

infrastructure/aat.tfvars, infrastructure/preview.tfvars
This reverts commit ecfc4177d89d3e520636982594948b9acdea3bcf.
=> Revert "SSCS-3441 Update idam redirect url for sidam migration (#209)"

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/service/MessageAuthenticationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/TribunalsServiceTest.java
Fix mockito deprecated library
=> [PREVIEW] Upgrade common library

build.gradle
=> SSCS-4659 - upgrade common lib

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
=> SSCS-4737 Make error message less misleading

build.gradle
Added High Wycombe for SL* post codes
=> update to add new venue

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CreateCaseInCcdTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/UpdateCaseInCcdTest.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/resources/json/syaWithMrnDateMoreThan13Months.json, src/test/resources/json/syaWithNoMrnDate.json
- If appeal does not contain an MRN then create incomplete case
- If appeal MRN date is greater than 13 months then create interloctory review case
=> SSCS-4956 Create appeal in different states

build.gradle
=> SSCS-5181 Venue Address Change (Milton Keynes) bump version

Jenkinsfile_nightly, security.sh
=> set up SSCS tribunals case api security scan

security.sh
=> use Dockerglue for SSCS tribunals case api security scan

security.sh
=> Rubyglue for SSCS tribunals case api security scan false positives

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/resources/sya/allDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithDifferentAddressCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressButNoAppellantContactDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressCcd.json, src/test/resources/sya/appealWithEvidenceDocumentsCcd.json, src/test/resources/sya/appellantPhoneNumberWithoutSpacesCcd.json, src/test/resources/sya/hearingWithSupportWithoutScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportAndScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportWithScheduleHearingCcd.json, src/test/resources/sya/ninoWithoutSpacesCcd.json, src/test/resources/sya/withoutEmailNotificationCcd.json, src/test/resources/sya/withoutHearingCcd.json, src/test/resources/sya/withoutNotificationCcd.json, src/test/resources/sya/withoutRepresentativeCcd.json, src/test/resources/sya/withoutRpcCcd.json, src/test/resources/sya/withoutSmsNotificationCcd.json
Jira: https://tools.hmcts.net/jira/browse/SSCS-4658
* Subscribe a rep to sms notifications if a mobile number is entered.
* Do not subscribe a rep to sms notifications if a landline is entered.
=> SSCS-4658: Subscribe a rep to sms notifications if a mobile is entered

Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/main.tf, infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, kubernetes/deployment.template.yaml
=> configure tribunal to point to sidam on the saat env

src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
Generate a tya number for a rep when a rep is added after sya.
=> SSCS-4442: Generate a tya number when no rep

build.gradle
=> fix gradlew functional task to make functional tests run in the pipeline

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
=> SSCS-5162 Internal server error - propagating error message to Front End

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
=> SSCS-5231 Tweaks to SYA Report

build.gradle
=> dependency check analyze runs twice

src/main/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraft.java, src/test/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraftTest.java
=> parse date strings into localdates

charts/sscs-tribunals-api/Chart.yaml
Let us see if this helm chart get installed.
=> SSCS-5497: bump version of helm chart

src/main/java/uk/gov/hmcts/reform/sscs/service/EventService.java
=> SSCS-5570 Logging – Check whether SSCS1 form is present

src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java
=> SSCS-5409 SSCS API – TYA – No events exist for this appeal

src/main/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraft.java, src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/EventControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/SubscriptionsControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/model/draft/SessionDraftTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/EventServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/MessageAuthenticationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/OtpGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/TribunalsServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraftTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SerializeJsonMessageManager.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SyaJsonMessageSerializer.java, src/test/resources/drafts/session-sample-esa.json
https://tools.hmcts.net/jira/browse/SSCS-5591
ESA Path
```
[ ] Yes
[X] No
```
=> SSCS-5574 implement full GET contract - ESA path

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/TribunalsCaseApiApplication.java
https://tools.hmcts.net/jira/browse/SSCS-5571
Update sscs-common version
```
[ ] Yes
[X] No
```
=> SSCS-5571 - update sscs-common version

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java
Add extra logging as requested by malik
=> SSCS-5707 - add extra logging to the test as requested by @malik

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/evidence/EvidenceDocumentUploadEndpointIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/e2e/resources/config/application_e2e.properties, src/main/resources/config/application.properties, src/test/resources/json/rpc.json, src/test/resources/sya/allDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithDifferentAddressCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressButNoAppellantContactDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressCcd.json, src/test/resources/sya/appealWithEvidenceDocumentsCcd.json, src/test/resources/sya/appellantNoContactDetailsCcd.json, src/test/resources/sya/appellantPhoneNumberWithoutSpacesCcd.json, src/test/resources/sya/hearingWithSupportEmptyCcd.json, src/test/resources/sya/hearingWithSupportWithoutScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportAndScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportWithScheduleHearingCcd.json, src/test/resources/sya/ninoWithoutSpacesCcd.json, src/test/resources/sya/wantsSupportWithoutArrangementsCcd.json, src/test/resources/sya/wantsSupportWithoutScheduleCcd.json, src/test/resources/sya/withoutEmailNotificationCcd.json, src/test/resources/sya/withoutHearingCcd.json, src/test/resources/sya/withoutNotificationCcd.json, src/test/resources/sya/withoutRepresentativeCcd.json, src/test/resources/sya/withoutSmsNotificationCcd.json, src/test/resources/sya/withoutWantsSupportCcd.json
=> Add new rpc email field to the json data used in tests

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ActionFurtherEvidenceDropdownHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/EventToFieldPreSubmitCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/HandleEvidenceEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/PreSubmitCallbackDispatcher.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/PreSubmitCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdCallbackController.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ActionFurtherEvidenceDropdownHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/HandleEvidenceEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/OutcomeServiceHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/PreSubmitCallbackDispatcherTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdCallbackControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-5918
- Add about to start callback to populate the dropdowns on the action further evidence event
```
[ ] Yes
[ x] No
```
=> SSCS-5918 Populate further evidence dropdown

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandlerTest.java
Set interlocReviewState for UPLOAD_FURTHER_EVIDENCE event
https://tools.hmcts.net/jira/browse/SSCS-5812
```
[ ] Yes
[X] No
```
=> SSCS-5812 Set interlocReviewState for UPLOAD_FURTHER_EVIDENCE event

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaAppellant.java
https://tools.hmcts.net/jira/browse/SSCS-5722
Normalise nino
```
[ ] Yes
[X] No
```
=> SSCS-5722 - Update sscs-common version for nino normalisation

src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java
=> minor refactor to reuse HearingTypeEnum

infrastructure/prod.tfvars
=> turn on send to dwp

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-5963
Ignore empty hearing dates
```
[ ] Yes
[X] No
```
=> SSCS-5963 - update sscs-robotics-common version

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-4067
Update sscs-common rc version
```
[ ] Yes
[X] No
```
=> SSCS-4067 - update sscs common rc version

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandlerTest.java, src/test/resources/callback/judgeDecisionAppealToProceedEventCallback.json, src/test/resources/callback/tcwDecisionAppealToProceedEventCallback.json
When you move a case out of interloc you need to attach a interloc
decision document. CCD does not enforce this so adding a presubmit
callback to check one has been set. We also need to make sure the doc is
a PDF so check this as well.
```
[ ] Yes
[ ] No
```
=> SSCS-6104 Validate Interloc Decision doc

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandlerTest.java
Validation that we have a decision document is not working adding more logging to work out why
=> Add extra logging

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java
Reverts hmcts/sscs-tribunals-case-api#639
=> Revert "fix functional tests"

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandlerTest.java
=> Add extra logging to find out why interloc decision document handler is

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java
Automatically trigger "Issue Further Evidence" event when user selects "Issue evidence to all parties"
=> SSCS-6317 - Automatically trigger "Issue Further Evidence" 

build.gradle, dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java
https://tools.hmcts.net/jira/browse/SSCS-6264
Update sscs-common version
```
[ ] Yes
[X] No
```
=> SSCS-6264 - update sscs-common version

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/resources/sya/allDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithDifferentAddressCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressButNoAppellantContactDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressCcd.json, src/test/resources/sya/appealWithEvidenceDocumentsCcd.json, src/test/resources/sya/appellantNoContactDetailsCcd.json, src/test/resources/sya/appellantPhoneNumberWithoutSpacesCcd.json, src/test/resources/sya/hearingWithSupportEmptyCcd.json, src/test/resources/sya/hearingWithSupportWithoutScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportAndScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportWithScheduleHearingCcd.json, src/test/resources/sya/ninoWithoutSpacesCcd.json, src/test/resources/sya/wantsSupportWithoutArrangementsCcd.json, src/test/resources/sya/wantsSupportWithoutScheduleCcd.json, src/test/resources/sya/withoutEmailNotificationCcd.json, src/test/resources/sya/withoutHearingCcd.json, src/test/resources/sya/withoutNotificationCcd.json, src/test/resources/sya/withoutRpcCcd.json, src/test/resources/sya/withoutSmsNotificationCcd.json, src/test/resources/sya/withoutWantsSupportCcd.json
https://tools.hmcts.net/jira/browse/SSCS-6407
- Set case code from dwp upload response event
- Set the case code when case is created
=> Sscs 6407 Set case code

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6408
=> SSCS-6408 Set the originating and presenting office dropdown

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/RecreateAppealPdfHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/RecreateAppealPdfHandlerTest.java
=> Sscs 6462 generate pdf fix

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCS-5655
Increase logging on case status changes
```
[ ] Yes
[X] No
```
=> SSCS-5655 - increase logging on case status changes

charts/sscs-tribunals-api/values.preview.template.yaml, charts/sscs-tribunals-api/values.yaml
=> Fix values

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
=> SSCS-6496 Set created in gaps from field

src/main/java/uk/gov/hmcts/reform/sscs/controller/TyaController.java, src/main/java/uk/gov/hmcts/reform/sscs/service/TribunalsService.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/TyaControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6691
TYA / TCAPI – Change exceptions to errors
```
[ ] Yes
[X] No
```
=> SSCS-6691 - return 404 (without exception)

src/main/java/uk/gov/hmcts/reform/sscs/controller/TyaController.java, src/main/java/uk/gov/hmcts/reform/sscs/service/TribunalsService.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/TyaControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/TribunalsServiceTest.java
=> SSCS-6691 TYA / TCAPI – Change exceptions to errors

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/DocumentType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentHandler.java, src/main/resources/config/application-local.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/fenoaction/FeNoActionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/fenoaction/FeNoActionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/BaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentHandlerTest.java, src/test/resources/callback/fenoaction/expectedFeNoActionAboutToStartCallbackResponse.json, src/test/resources/callback/fenoaction/feNoActionAboutToStartCallback.json, src/test/resources/callback/fenoaction/feNoActionAboutToSubmitCallback.json, src/test/resources/callback/uploaddocument/expectedUploadDocumentCallbackResponse.json, src/test/resources/callback/uploaddocument/uploadDocumentCallback.json
https://tools.hmcts.net/jira/browse/SSCS-6692
=> SSCS-6692 dwpState field to flag FE

build.gradle
=> SSCS-6525 Common – SSCS1 form generation appeal reason field switch

src/main/java/uk/gov/hmcts/reform/sscs/service/TribunalsService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/TribunalsServiceTest.java
=> SSCS-6727 TYA/TCAPI - 'Appeal not found for appeal number' Exception

build.gradle, charts/sscs-tribunals-api/values.preview.template.yaml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/uploaddocument/UploadDocumentHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/resources/callback/interlocEventCallback.json
https://tools.hmcts.net/jira/browse/SSCS-6684
auto add boolean
```
[ ] Yes
[x] No
```
=> Sscs 6684 boolean links

src/test/java/uk/gov/hmcts/reform/sscs/service/conversion/ImageConverterTest.java
remove output.pdf created from a unit test
=> Remove unwanted output.pdf file

src/main/java/uk/gov/hmcts/reform/sscs/controller/EvidenceManagementController.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/PostCodeController.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/TyaController.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/SyaControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6730
=> SSCS-6730 add validation to the PUT endpoint draft

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addrep/AddRepEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postpone/DwpState.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addrep/AddRepAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6308
=> SSCS-6308 Rep added to case flag

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6826
=> SSCS-6826 Use direction and decision objects

src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/SyaControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
=> SSCS-6812 S&R – Multiple calls are made to CCD which are unnecessary

Jenkinsfile_CNP, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/state.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/SSCS-6928
=> SSCS-6928 Deploy to demo

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/DecisionIssuedIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/DwpState.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java, src/test/resources/callback/decisionIssuedForPreview.json, src/test/resources/callback/directionIssuedForPreview.json
https://tools.hmcts.net/jira/browse/SSCS-6931
=> SSCS-6931 Issue direction and decision post valid states

build.gradle
=> SSCS-6791 SYA/tribunal case API – Change Norwich DRT to Sheffield DRT

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CreateCaseInCcdTest.java
https://tools.hmcts.net/jira/browse/SSCS-6836
=> SSCS-6836 Add missing fields to java model

src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
=> minor refactor to make method smaller and clearer

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/SscsPdfService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SscsPdfServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-6970
=> SSCS-6970 Move service to tribunals from pdf common

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reissuefurtherevidence/ReissueFurtherEvidenceAboutToSubmitHandler.java
https://tools.hmcts.net/jira/browse/SSCS-6640
=> SSCS-6640 Stop reissuing evidence to DWP

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandler.java
https://tools.hmcts.net/jira/browse/SSCS-6978
=> SSCS-6978: improve the logs

src/e2e/resources/handlers/uploaddocument/uploadDocumentCallback.json
Fix functional test
```
[ ] Yes
[x] No
```
=> Fix urls in test

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/DirectionIssuedIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6846
=> SSCS-6846 Change directions notice

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocReviewState.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwplapse/DwpLapseCaseHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7031
=> Sscs 7031 interloc referral date

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionTypeItemList.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7027
=> SSCS-7027 Rename direction type options

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7056
=> SSCS-7056 Fix bug for interloc state in action further evidence event

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdminSendToWithDwpIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtowithdwp/AdminSendToWithDwpAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtowithdwp/AdminSendToWithDwpAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java, src/test/resources/callback/adminSendToWithDwp.json
https://tools.hmcts.net/jira/browse/SSCS-6959
=> SSCS-6959 Callback handler for adminSendToWithDwp event

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/timeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7066
=> SSCS-7066 Move TL1 to DWP tab

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7070
=> SSCS-7070 Set interloc referral date for post-valid interloc cases

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/HmctsResponseReviewedIt.java
=> SSCS-6809 Changes to support new PIP AE office added by DWP

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7138
=> SSCS-7138 Fix for dynamic lists clearing when back button pressed

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7128
=> SSCS-7128 Add appeal to proceed option for all states when issuing direction

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java
https://tools.hmcts.net/jira/browse/SSCS-7148
=> SSCS-7148 Use common library for dwp regional center

config/checkstyle/checkstyle.xml, src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/reissuefurtherevidence/ReissueFurtherEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/reissuefurtherevidence/ReissueFurtherEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaEvidence.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaMrn.java, src/main/java/uk/gov/hmcts/reform/sscs/exception/AppealNotFoundException.java, src/main/java/uk/gov/hmcts/reform/sscs/healthcheck/DocmosisHealthIndicator.java, src/main/java/uk/gov/hmcts/reform/sscs/service/MessageAuthenticationService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/OtpGenerator.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtodormantappealstate/AdminSendToDormantAppealStateAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/appeallapsed/AppealLapsedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/appealwithdrawn/AppealWithdrawnAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/healthcheck/TribunalCaseApiHealthAggregatorTest.java
=> fix imports because fo the checkstyle upgrade version

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7289
=> SSCS-7289-Handle empty case code

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7289
=> SSCS-7289 change logic to not overwrite case code

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CreateBundleIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToStartHandlerTest.java, src/test/resources/callback/createBundleCallback.json
https://tools.hmcts.net/jira/browse/SSCS-7204
=> SSCS-7204 Fix for empty DWP bundle docs

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/HmctsResponseReviewedIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java, src/test/resources/callback/hmctsResponseReviewedCallback.json
https://tools.hmcts.net/jira/browse/SSCS-7123
=> SSCS-7123 Prevent DD case code

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7001
=> Sscs 7001 ignore coversheet

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7052
=> SSCS-7052 Update RPC when postcode is changed

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6746
=> SSCS-6746 Show warning for filename with just spaces

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7349
=> SSCS-7349 Set interloc referral date for reinstate appeal event

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/linkcase/LinkCaseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/associatecase/LinkCaseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6710
=> SSCS-6710 Reciprocal link to all linked cases

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/linkcase/LinkCaseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7378
=> SSCS-7378 Create reciprocal link for associated case

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/HmctsResponseReviewedIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/subscriptionupdated/SubscriptionUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/subscriptionupdated/SubscriptionUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7256
=> SSCS-7256 Updated subscription callback generate tya

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AbstractEventIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controller/LivenessControllerTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/postcode/PostCodeEndpointsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/SubscriptionEndPointsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/TyaEndpointsIt.java, src/IntegrationTests/resources/config/application_it.properties, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7402
=> SSCS-7402 Move send to dwp event to evidence share

build.gradle
=> Fixed apache tika vulnerabilities

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7413
=> SSCS-7413 Change undefined rep name to null

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeQuestionService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeQuestionServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7521
=> SSCS-7521 Build points extractor for decision notices

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7536
* Upping sscs-common version to 3.2.27
* Adding validation for decision date field to mid event callback handler
```
[ ] Yes
[x ] No
```
=> SSCS-7536 Adding decision date validation to mid event handler

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/ActivityQuestion.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/ActivityType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/AwardType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/PointsCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/ActivityQuestionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/ActivityTypeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/PointsConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7537
*  Adding points based validation to WriteFinalDecisionAboutToSubmitHandler
```
[ ] Yes
[ x] No
```
=> SSCS-7537 Adding about to submit handler points validation logic

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7525
=> SSCS-7523 Set outcome and dwp state for final decision notice

build.gradle, dependency-check-suppressions.xml
=> SSCS-7550: New AirLookup

build.gradle, dependency-check-suppressions.xml
=> SSCS-7545 MYA - Not all word documents are converting to PDF when upl

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7584
=> SSCS-7584 Add question for dwp compare mobility and set outcome

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/DecisionIssuedIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/DirectionIssuedIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/ReissueFurtherEvidenceIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controller/SyaControllerTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/evidence/EvidenceDocumentUploadEndpointIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenIdamService.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/main/resources/config/application.properties
=> SSCS-7473 Sscs-common bump

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/IssueFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/resources/callback/issueFinalDecisionCallback.json
https://tools.hmcts.net/jira/browse/SSCS-7507
=> SSCS-7507 Issue final decision notice

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/IssueFinalDecisionIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/BaseHandler.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/dwplapse/DwpLapseCaseHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/sscs1casecreation/Sscs1PdfHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/timeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenIdamService.java, src/e2e/resources/handlers/writefinaldecision/writeFinalDecisionCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java, src/test/resources/callback/writeFinalDecision.json
https://tools.hmcts.net/jira/browse/SSCS-7616
=> SSCS-7616 End to end tests for write final decision

charts/sscs-tribunals-api/requirements.yaml
=> SSCS-7540- Remove redundant file

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7623
=> SSCS-7623 Handle empty hearings for generating decision notices

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/DirectionOrDecisionIssuedTemplateBody.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/WriteFinalDecisionTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7555
https://tools.hmcts.net/jira/browse/SSCS-7556
https://tools.hmcts.net/jira/browse/SSCS-7557
Moving writeFinalDecision properties of payload into nested class.
```
[ ] Yes
[x ] No
```
=> SSCS-7555 Extracting write final decision fields into nested class

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/WriteFinalDecisionTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java, src/test/resources/callback/writeFinalDecision.json
https://tools.hmcts.net/jira/browse/SSCS-7557
Adding reasons for decision to payload
```
[ ] Yes
[x ] No
```
=> SSCS-7557 Adding reasons for decision to payload

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/e2e/resources/handlers/writefinaldecision/writeFinalDecisionCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/WriteFinalDecisionTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7558
=> SSCS-7558 Final Decision Notice letter fields for attended hearing and hearing type

src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7678
Refactoring unit tests specific to previewing document to simplify code
```
[ ] Yes
[ x] No
```
=> SSCS-7678 Refactoring unit tests specific to previewing document to simplify code

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackController.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/DirectionOrDecisionIssuedTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/EvidenceUploadControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/SubscriptionsControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/TyaControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaCaseWrapperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/MessageAuthenticationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/coversheet/CoversheetServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/event/PaperCaseEventFilterUtilTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/pdf/util/PdfDateUtilTest.java, src/test/java/uk/gov/hmcts/reform/sscs/thirdparty/pdfservice/DocmosisPdfServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/thirdparty/pdfservice/OldPdfServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/DateTimeUtilsTest.java, src/test/resources/callback/issueFinalDecisionCallback.json
https://tools.hmcts.net/jira/browse/SSCS-7666
=> SSCS-7666 Set issue date and generate date on final decision notice

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/e2e/resources/handlers/writefinaldecision/writeFinalDecisionCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/WriteFinalDecisionTemplateBody.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeServiceTest.java, src/test/resources/callback/writeFinalDecision.json
https://tools.hmcts.net/jira/browse/SSCS-7637
https://tools.hmcts.net/jira/browse/SSCS-7697
* Adding non-descriptor flow
* Changing reasons field from string to collection
* Adding anything else field
```
[ ] Yes
[ x] No
```
=> SSCS-7637 SSCS-7697 Non descriptor flow, changes to reasons field and anything else field

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/FooterService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/PreSubmitCallbackDispatcherTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtowithdwp/AdminSendToWithDwpAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/fehandledoffline/FeHandledOfflineHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/EvidenceManagementControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/StatementControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/TribunalsControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/FooterServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/pdf/StoreEvidenceDescriptionServiceTest.java, src/test/resources/callback/writeFinalDecisionManualUploadDescriptor.json, src/test/resources/callback/writeFinalDecisionManualUploadNonDescriptor.json
https://tools.hmcts.net/jira/browse/SSCS-7668
=> SSCS-7668 Manual upload decision notice

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7689
Adding validation to prevent non-sensical options on the award page.
```
[ ] Yes
[x] No
```
=> SSCS-7589 Adding initial logic to perform award type validation

build.gradle
=> SSCS-7712: Caseloader – Re-requesting a new IDAM token before updatin

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/AwardType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/PointsCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/PointsConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTest.java, src/test/resources/callback/writeFinalDecisionDescriptorNotConsidered.json
https://tools.hmcts.net/jira/browse/SSCS-7661
* Modifying business logic and test, and validation to handle the "notConsidered" rate
```
[ ] Yes
[x] No
```
=> Sscs 7661 activities validation

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java
https://tools.hmcts.net/jira/browse/SSCS-7637
Adding integration test for callToAboutToSubmitHandler_willWriteDraftFinalDecisionToCaseForNonDescriptorRoute
```
[ ] Yes
[x ] No
```
=> Sscs 7637 adding integration test

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/IssueFinalDecisionIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackController.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackControllerTest.java, src/test/resources/callback/issueFinalDecisionCallback.json, src/test/resources/callback/writeFinalDecisionManualUploadDescriptor.json, src/test/resources/callback/writeFinalDecisionManualUploadNonDescriptor.json
https://tools.hmcts.net/jira/browse/SSCS-7728
* Removing fields and local for issue document date and filename.
* Setting user name on pdf payload
* Ensuring we remove draft status from issue document
```
[ ] Yes
[ x] No
```
=> SSCS-7728 PIP DN Tidy Up

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/IssueFinalDecisionIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/resources/callback/issueFinalDecisionDescriptorCallback.json, src/test/resources/callback/issueFinalDecisionDescriptorUploadCallback.json, src/test/resources/callback/issueFinalDecisionNonDescriptorCallback.json, src/test/resources/callback/issueFinalDecisionNonDescriptorUploadCallback.json
https://tools.hmcts.net/jira/browse/SSCS-7707
https://tools.hmcts.net/jira/browse/SSCS-7710
* Moving setting of outcome code out of WriteFinalDecision submit event and into IssueFinalDecision submit event
```
[ ] Yes
[x ] No
```
=> SSCS-7707 SSCS-7710 Refactor setting of outcome code

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaCaseWrapper.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/resources/sya/allDetails.json, src/test/resources/sya/allDetailsCcd.json, src/test/resources/sya/withoutRpcCcd.json
https://tools.hmcts.net/jira/browse/SSCS-7740
=> SSCS-7740 Add PCQ id

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandlerTest.java, src/test/resources/callback/adjournCaseYesNoYes.json
https://tools.hmcts.net/jira/browse/SSCS-7626
* Adding mid event handler and validation for the Directions Due Date page
```
[ ] Yes
[x] No
```
=> Sscs 7626 can case be listed right away

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionDraft.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionPcqId.java, src/main/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraft.java, src/test/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraftTest.java
https://tools.hmcts.net/jira/browse/SSCS-7741
https://tools.hmcts.net/jira/browse/PCQ-508
=> Sscs 7741 pcq id draft store

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7753
* Implementing changes to logic of generating outcome and confirmed/set aside.
```
[ ] Yes
[x] No
```
=> Sscs 7753 award logic changes

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/coversheet/CoversheetService.java
https://tools.hmcts.net/jira/browse/SSCS-7739
```
[ ] Yes
[ ] No
```
=> SSCS-7739 Bump sscs-pdf-email-common

Jenkinsfile_parameterized, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/tya/GetAppealStatus.java, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCS-7739
```
[ ] Yes
[ ] No
```
=> Sscs 7739. - Domosis URL Config (reapproval)

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandlerTest.java, src/test/resources/callback/adjournCaseYesNoNo.json
https://tools.hmcts.net/jira/browse/SSCS-7631
* Modifying existing validation to only apply if issuing directions to parties
```
[ ] Yes
[x] No
```
=> SSCS-7631 Modifying existing validation to be conditional and adding validation for next hearing page

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/DescriptorLexicographicalComparator.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/DescriptorComparatorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SyaJsonMessageSerializer.java
https://tools.hmcts.net/jira/browse/SSCS-7754
* Ordering descriptors lexicographically and fixing SyoJsonMessageSerializer compilation errors
```
[ ] Yes
[x] No
```
=> SSCS-7754 Ordering descriptors lexicographically

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandlerTest.java, src/test/resources/callback/adjournCaseYesNoNo.json
https://tools.hmcts.net/jira/browse/SSCS-7631
* Changes in line with A/C changes
* fixing bug with validation of firstAvailableDateAfter scenario
```
[ ] Yes
[x] No
```
=> SSCS-7631 Changes in line with A/C changes, and fixing bug with validation of firstAvailableDateAfter scenario

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/PreviewDocumentService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/PreviewDocumentServiceTest.java, src/test/resources/callback/adjournCaseManuallyGenerated.json
https://tools.hmcts.net/jira/browse/SSCS-7670
=> SSCS-7670 Move draft adjournment to sscs document

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7784
=> SSCS-7784 Write adjourned language interpreter to hearing options

build.gradle
uses PR https://github.com/hmcts/sscs-pdf-email-common/pull/309
=> SSCS-7598 - Tiff image conversion

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/DirectionOrDecisionIssuedTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7752
* Adding appointee full name to decision notice payload
```
[ ] Yes
[x] No
```
=> SSCS-7752 Adding appointee full name to decision notice payload

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/NotListableIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/notlistable/NotListableAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/notlistable/NotListableMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/notlistable/NotListableAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/notlistable/NotListableMidEventValidationHandlerTest.java, src/test/resources/callback/notListableCallback.json
https://tools.hmcts.net/jira/browse/SSCS-7607
=> SSCS-7607 Not listable due date

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatenotlistable/UpdateNotListableAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatenotlistable/UpdateNotListableAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7610
=> Sscs 7610 update not listable directions fulfilled

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/HearingType.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/resources/callback/adjournCaseGeneratedTelephoneWhenCaseNotListedStraightAwayWithoutDirectionsMade.json
https://tools.hmcts.net/jira/browse/SSCS-7642
* Adding handling of telephone hearings
```
[ ] Yes
[x] No
```
=> SSCS-7642 Adding handling of telephone hearings

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AbstractEventIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/HearingType.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/AdjournCaseTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/resources/callback/adjournCaseGeneratedPaperWhenCaseNotListedStraightAwayWithoutDirectionsMade.json
https://tools.hmcts.net/jira/browse/SSCS-7644
Adding paper hearing handling
```
[ ] Yes
[x] No
```
=> SSCS-7644 Adding paper hearing handling

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/notlistable/NotListableAboutToSubmitHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/updatenotlistable/UpdateNotListableAboutToSubmitHandlerTest.java, src/e2e/resources/handlers/adjourncase/adjournCaseCallback.json, src/e2e/resources/handlers/notlistable/notListableCallback.json, src/e2e/resources/handlers/updatenotlistable/updateNotListableCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/notlistable/NotListableAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/notlistable/NotListableAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7818
=> SSCS-7818 Functional tests

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestinfo/RequestInfoIncompleteApplicationAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7038
SSCS Common bump and remove refs to Outcome state
```
[ ] Yes
[X] No
```
=> SSCS Common bump and remove refs to Outcome state

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/IssueAdjournmentIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionPcqId.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7871
=> SSCS-7871 Adjournment notice issued DWP state

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reissuedocument/ReissueDocumentAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reissuedocument/ReissueDocumentAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reissuedocument/ReissueDocumentAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7790
* Adding Adjourn Case Reissue Handling
```
[ ] Yes
[x] No
```
=> SSCS-7790 Adding Adjourn Case Reissue Handling

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7870
=> SSCS-7870 only clear adjourn case data when no draft exists

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java, src/e2e/resources/handlers/adjourncase/adjournCaseCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reissuedocument/ReissueDocumentAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/AdjournCaseTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reissuedocument/ReissueDocumentAboutToStartHandlerTest.java, src/test/resources/callback/adjournCaseGeneratedFaceToFaceWhenCaseNotListedStraightAwayWithoutDirectionsMade.json, src/test/resources/callback/adjournCaseGeneratedPaperWhenCaseNotListedStraightAwayWithoutDirectionsMade.json, src/test/resources/callback/adjournCaseGeneratedTelephoneWhenCaseNotListedStraightAwayWithoutDirectionsMade.json, src/test/resources/callback/adjournCaseGeneratedVideoWhenCaseNotListedStraightAwayWithDirectionsMade.json, src/test/resources/callback/adjournCaseGeneratedVideoWhenCaseNotListedStraightAwayWithoutDirectionsMade.json, src/test/resources/callback/adjournCaseValidSubmissionWithNullGeneratedDate.json, src/test/resources/callback/adjournCaseValidSubmissionWithSetGeneratedDate.json, src/test/resources/callback/issueAdjournmentCallback.json
https://tools.hmcts.net/jira/browse/SSCS-7866
Changing anythingElse to additionalDirections and issue adjournment event type
```
[ ] Yes
[x] No
```
=> SSCS-7866 Judges' feedback display changes

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestinfo/RequestInfoIncompleteApplicationAboutToSubmitHandlerTest.java
=> SSCS-7037 Remove non used PENDING_APPEAL usage

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/HearingType.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7869
* Changing existing next hearing type "hearing" prefixes to the entire hearing type string, to allow for "paper" hearing to be replaced by "decision on the papers"
* Ensuring that sessions/hours is pluralised correctly
```
[ ] Yes
[x] No
```
=> SSCS-7869 Judges feedback document template changes

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7834
* Adding validation for Joint Party DOB
```
[ ] Yes
[x] No
```
=> SSCS-7834 Adding joint party DOB validation

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7835
* Adding joint party nino validation tests
```
[ ] Yes
[x] No
```
=> Sscs 7835 adding nino validation

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7837
* Upgrading to latest common with address validation and adding address validation tests
```
[ ] Yes
[x] No
```
=> SSCS-7837 Upgrading to latest common with address validation and adding address validation tests

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7831
=> SSCS-7831 Auto assign case code for UC upload resonse

audit.json
=> added more url in audit.json

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/AdjournCaseTemplateBody.java, src/main/java/uk/gov/hmcts/reform/sscs/service/LanguageService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/LanguageServiceTest.java, src/test/resources/callback/adjournCaseGeneratedFaceToFaceWithInterpreterNotRequiredAndLanguageSet.json, src/test/resources/callback/adjournCaseGeneratedFaceToFaceWithInterpreterRequiredAndLanguageNotSet.json, src/test/resources/callback/adjournCaseGeneratedFaceToFaceWithInterpreterRequiredAndLanguageSet.json
https://tools.hmcts.net/jira/browse/SSCS-7875
* Adding LanguageService and adding interpreter description to payload body
```
[ ] Yes
[x] No
```
=> Sscs 7875 adding interpreter description to payload body

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7989
* Upgrading tests for identity name refactor
```
[ ] Yes
[x] No
```
=> SSCS-7989 Upgrading tests for identity name refactor

security.sh
=> Fixed proxy connection error

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackController.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7868
Change venue list to be a list with unprefixed alphabetically sorted venues for default PRC first, followed by a list of RPC-prefixed venues for other RPCs
```
[ ] Yes
[x] No
```
=> Sscs 7868 Spike: mid event callback for venue list alternate

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackController.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7868
Upgrading to commons for SscsCaseData with adjournCaseNextHearingVenueSelected as DynamicList
Adding mid event callback controller for population of dynamic venue list matching RPC of case
```
[ ] Yes
[x] No
```
=> SSCS-7868 Spike : Adding mid event callback controller for population of dynamic venue list

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/UpdateCaseInCcdTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/BaseHandler.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/tya/GetAppealStatus.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/isscottish/IsScottishHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/isscottish/IsScottishHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/resources/sya/allDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithDifferentAddressCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressButNoAppellantContactDetailsCcd.json, src/test/resources/sya/allDetailsWithAppointeeWithSameAddressCcd.json, src/test/resources/sya/appealWithEvidenceDocumentsCcd.json, src/test/resources/sya/appellantNoContactDetailsCcd.json, src/test/resources/sya/appellantPhoneNumberWithoutSpacesCcd.json, src/test/resources/sya/hearingWithSupportEmptyCcd.json, src/test/resources/sya/hearingWithSupportWithoutScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportAndScheduleHearingCcd.json, src/test/resources/sya/hearingWithoutSupportWithScheduleHearingCcd.json, src/test/resources/sya/ninoWithoutSpacesCcd.json, src/test/resources/sya/wantsSupportWithoutArrangementsCcd.json, src/test/resources/sya/wantsSupportWithoutScheduleCcd.json, src/test/resources/sya/withoutEmailNotificationCcd.json, src/test/resources/sya/withoutHearingCcd.json, src/test/resources/sya/withoutNotificationCcd.json, src/test/resources/sya/withoutRpcCcd.json, src/test/resources/sya/withoutSmsNotificationCcd.json, src/test/resources/sya/withoutWantsSupportCcd.json
SSCS 8001 - Restrict isScottish handler to creation events
```
[ ] Yes
[X] No
```
=> SSCS 8001 - Restrict isScottish handler to creation events

audit.json
=> fix security scan step for jenkins nightly

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentDownloadService.java
N/A
Sonar bug fixes and CVE fixes
```
[ ] Yes
[x] No
```
=> Resolving potential NPEs found by sonar

src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentDownloadService.java
N/A
* Fixing potential NPE by now only calling response.getBody() once
```
[ ] Yes
[x] No
```
=> Fixing potential NPE by now only calling response.getBody() once

build.gradle, dependency-check-suppressions.xml, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/AppellantStatementTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/EvidenceUploadTest.java, src/e2e/resources/config/application_e2e.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/resources/config/application-local.properties, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
=> Sscs 7806 reinstatement requests 2

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsSubmittedHandler.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsSubmittedHandlerTest.java
=> Wla 698 add interloc review welsh

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/DirectionIssuedIt.java, src/IntegrationTests/resources/config/application_it.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionTypeItemList.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/resources/callback/directionIssuedReinstatementRequest.json
=> Sscs 7809 resintatement judge

src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java, src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SerializeJsonMessageManager.java, src/test/resources/tya/appealReceivedMya.json, src/test/resources/tya/dormantMya.json, src/test/resources/tya/dwpRespondMya.json, src/test/resources/tya/hearingAdjournedCcd.json, src/test/resources/tya/hearingAdjournedMya.json, src/test/resources/tya/hearingMya.json, src/test/resources/tya/notListableMya.json
https://tools.hmcts.net/jira/browse/SSCS-7775
```
[ ] Yes
[ ] No
```
=> SSCS-7775: MYA - status and hide hearing details for Adjourn hearings

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/OriginalSenderItemList.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7998
=> SSCS-7998 Confidential request

dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java
SSCS-8194 - Next hearing date text
=> SSCS-8194 - Next hearing date text

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/subscriptionupdated/SubscriptionUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/subscriptionupdated/SubscriptionUpdatedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8202
```
[ ] Yes
[x] No
```
=> SSCS 8202 Added joint party tya number

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenLoginTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CreatedCcdCase.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SscsMyaBackendRequests.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/CreateCaseController.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginService.java, src/main/resources/json/ccd_case.json, src/test/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8204
Changes for joint party login to MYA/COR
```
[ ] Yes
[x] No
```
=> SSCS 8204 use rc common

build.gradle, charts/sscs-tribunals-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-8204
```
[ ] Yes
[x] No
```
=> SSCS 8204 upped common version

charts/sscs-tribunals-api/values.aat.template.yaml
SSCS-8204
```
[ ] Yes
[x] No
```
=> Sscs 8204 fix joint party tya

src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaHearingOptions.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaOptions.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SyaJsonMessageSerializer.java, src/test/resources/sya/hearingWithOptions.json, src/test/resources/sya/hearingWithOptionsCcd.json
https://tools.hmcts.net/jira/browse/SSCS-7814
```
[ ] Yes
[X] No
```
=> Sscs 7814: SYA - Select all the suitable options for you to take part in the hearing

src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7957
```
[ ] Yes
[X] No
```
=> SSCS-7957:Joint party uploading evidence to MYA

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/makecaseurgent/MakeCaseUrgentAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/makecaseurgent/MakeCaseUrgentAboutToSubmitHandlerTest.java
=> SSCS-7985: CCD UI – Repurpose the makeCaseUrgent event

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8185
=> SSCS-8185 Set confidential case fields when request received in prep for Gaps

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/elementsdisputed/ElementsDisputedMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/elementsdisputed/ElementsDisputedMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7929
=> SSCS-7929 Response reviewed elements and issues

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CcdEventResponse.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CcdMidEventControllerFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CcdMidEventControllerIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/BaseFunctionTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SscsMyaBackendRequests.java, src/e2e/resources/handlers/writefinaldecision/writeFinalDecisionCallback.json
SSCS-8295 - MidEvent Functional Tests
Added functional tests for:
- ccdMidEvent
- ccdMidEventAdjournCasePopulateVenueDropdown 
- ccdMidEventPreviewFinalDecision 
- ccdMidEventPreviewAdjournCase 
- ccdMidEventAdminRestoreCases
=> SSCS-8295 - MidEvent Functional Tests

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaActivityQuestion.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsAndActivitiesCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeQuestionService.java
https://tools.hmcts.net/jira/browse/SSCS-7515
https://tools.hmcts.net/jira/browse/SSCS-7515
```
[ ] Yes
[x] No
```
=> SSCS-7515-SSCS-7516 Fixing issue of scoring with question answers not clearing when different activities are selected

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceHandler.java, src/test/resources/callback/uploaddocument/expectedUploadDocumentFECallbackResponse.json
=> SSCS-8323 Set evidence handled flag on upload document FE

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-7515
https://tools.hmcts.net/jira/browse/SSCS-7516
https://tools.hmcts.net/jira/browse/SSCS-7565
https://tools.hmcts.net/jira/browse/SSCS-7566
Upping commons version to fix ccd definition types
```
[ ] Yes
[x] No
```
=> Sscs 7515 sscs 7516 sscs esa activities and scores fix

Jenkinsfile_nightly, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-8321
Fix nightly tests
```
[ ] Yes
[x] No
```
=> sscs 8321 point at aat not staging

build.gradle
=> SSCS-8214 upgrade sscs-common

audit.json
=> fixed the security sccan

dependency-check-suppressions.xml
=> Suppress kotlin library dependency till end of november

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-7566
Upping commons update to include display order in fixed lists
```
[ ] Yes
[x] No
```
=> Sscs 7566 commons update

build.gradle, dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/SubscriptionEndPointsIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenLoginTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SubscriptionTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/AssociatedCaseLinkHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/admin/RestoreCasesService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/AssociatedCaseLinkHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/admin/RestoreCasesServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8330
=> SSCS-8330 Refactor after move to Elastic Search

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8324
```
[ ] Yes
[ ] No
```
=> SSCS-8324 Make docs added in hearings add to bundles

README.md, build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipWriteFinalDecisionMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8008
=> SSCS-8008 Summary of outcome show condition

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8357
=> SSCS-8357 Set case code for UC response reviewed event

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/amendelementsissues/AmendElementsIssuesAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/amendelementsissues/AmendElementsIssuesAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/elementsdisputed/ElementsDisputedMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/amendelementsissues/AmendElementsIssuesAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/amendelementsissues/AmendElementsIssuesAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/elementsdisputed/ElementsDisputedMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8359
=> SSCS-8359 Amend elements and issues event

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/MidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/elementsdisputed/ElementsDisputedMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandlerTestBase.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipWriteFinalDecisionMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8346
=> SSCS-8346 Schedule2 optional and test refactor

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addrep/AddRepEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postpone/PostponeHearingHandler.java
https://tools.hmcts.net/jira/browse/SSCS-8275
=> SSCS-8275 Move class variables to local

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTestBase.java
https://tools.hmcts.net/jira/browse/SSCS-8370
=> SSCS-8370 Send other panel member field to ESA decision notice

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaAllowedOrRefusedCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaSchedule3QuestionKey.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/PipDecisionNoticeOutcomeService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaSchedule3QuestionKeyTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionAboutToSubmitHandlerTest.java
Correcting page flow and award logic
```
[ ] Yes
[x] No
```
=> SSCS-7578 Correcting page flow and award logic

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandler.java
* Ensuring that we set the correct flag for displaying schedule 3 activities page.
* Only taking into account questions that have been selected when summing total points in validation handler
```
[ ] Yes
[x] No
```
=> SSCS-7578 Show activities page fix

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/WriteFinalDecisionTemplateBody.java
Adding further payload fields
```
[ ] Yes
[x] No
```
=> SSCS-7578 Adding further payload fields

src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ThreadRunnable.java
=> SSCS-8379 ThreadSafe test

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaAllowedOrRefusedCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario10Content.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario10Test.java
Added a Scenario 10 when in the user journey they choose it's a not a wca appeal.
=> SSCS 8308 in flux scenario 10

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/EsaDecisionNoticeFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceBase.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaTemplateContent.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaTemplateComponentId.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario10Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario5Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario6Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario7Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario8Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario9Content.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/WriteFinalDecisionTemplateBody.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario10Test.java
=> SSCS-8308 - Reassess the award changes

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
Reverts hmcts/sscs-tribunals-case-api#1510
=> Revert "Added address validation"

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaAllowedOrRefusedCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaTemplateContent.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario4Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario6Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario9Content.java, src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTestBase.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipWriteFinalDecisionPreviewDecisionServiceTest.java
* Changes to support manual upload route
```
[ ] Yes
[x] No
```
=> SSCS-7578 Changes to support manual upload route

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeQuestionService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeQuestionServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7580
* Schedule 3 descriptor order and further tests for allowed/refused scenarios.
* Correcting question key in existing tests
```
[ ] Yes
[x] No
```
=> SSCS-7580 Schedule 3 descriptor order and further tests

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaTemplateContent.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario3Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario7Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario8Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario9Content.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario3Test.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario7Test.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario8Test.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario9Test.java
https://tools.hmcts.net/jira/browse/SSCS-8413
=> Sscs 8413 disablement content

build.gradle
SSCS-8405 - Update Venue List
Change sscs-common lib to point to https://github.com/hmcts/sscs-common/pull/620
=> SSCS-8405 - Update Venue List

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaActivityType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaAllowedOrRefusedCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaSchedule3QuestionKey.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaActivityQuestionKeyTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaActivityTypeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaSchedule3QuestionKeyTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java
Changes in line with commons refactor of SscsEsaCaseData
```
[ ] Yes
[x] No
```
=> SSCS-7578 Changes in line with commons refactor of SscsEsaCaseData

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceBase.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaAllowedOrRefusedCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesCondition.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipWriteFinalDecisionPreviewDecisionService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTestBase.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipWriteFinalDecisionPreviewDecisionServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8048
Changes in line with moving wcaAppeal field to inside SscsEsaCaseData
Restructuring test to make it more generic
```
[ ] Yes
[x] No
```
=> SSCS-8048 Moving wca appeal field

build.gradle
=> resolve CVE-2020-13954

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcWriteFinalDecisionMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/uc/UcIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/uc/UcIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTestBase.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcPointsRegulationsAndSchedule7ActivitiesConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcWriteFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcWriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcWriteFinalDecisionPreviewDecisionServiceTest.java
Incorporates https://github.com/hmcts/sscs-common/pull/624 for small changes to https://github.com/hmcts/sscs-common/pull/617
=> small changes to the domain for PR 617

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/timeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java
=> SSCS-7789 Handle Multiple TL1 Forms

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/UcDecisionNoticeFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcNewTemplateContent.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/newscenarios/NewScenario1Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/scenarios/UcScenario.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/newscenarios/NewUcScenario1Test.java
https://tools.hmcts.net/jira/browse/SSCS-8080
```
[ ] Yes
[ ] No
```
=> SSSCS-8080:UC Decision notice – Refused All

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/EsaDecisionNoticeFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/UcDecisionNoticeFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaTemplateContent.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcNewTemplateContent.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcOldTemplateContent.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario3Test.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario4Test.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenarioHearingTypeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/scenarios/UcScenario4Test.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/scenarios/UcScenarioHearingTypeTest.java
=> SSCS-8081 Changing "an issue" to "in issue"

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/newscenarios/NewScenario7Content.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/newscenarios/NewUcScenario7Test.java
https://tools.hmcts.net/jira/browse/SSCS-8083
adding missing scenario 7 sentence
```
[ ] Yes
[x] No
```
=> Sscs 8083 adding missing scenario 7 sentence

src/main/java/uk/gov/hmcts/reform/sscs/controller/CreateCaseController.java
=> added representative for mya test

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CreatedCcdCase.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SscsMyaBackendRequests.java
=> added repre for mya test

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/EsaDecisionNoticeFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/Scenario10Content.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario10Test.java
https://tools.hmcts.net/jira/browse/SSCS-8453
* Removing paragraph from non-WCA templates
```
[ ] Yes
[x] No
```
=> Removing paragraph from non-WCA templates

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/UcDecisionNoticeFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/newscenarios/NewScenario4Content.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/scenarios/UcScenario.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/newscenarios/NewUcScenario4Test.java
https://tools.hmcts.net/jira/browse/SSCS-8469
Updating to content from judges
```
[ ] Yes
[x] No
```
=> sscs 8469 changes to content for scenario 4

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/provideappointeedetails/ProvideAppointeeDetailsAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/provideappointeedetails/ProvideAppointeeDetailsAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8334
=> Sscs 8334 provide appointee details event

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8326
=> Sscs 8326 death of appellant

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8327
=> SSCS-8327 Add appointee for death of appellant event

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenLoginTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SubscriptionTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java
https://tools.hmcts.net/jira/browse/SSCS-8482
=> SSCS-8482 Add sleep for randomly failing functional test

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/editbundle/EditBundleAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/editbundle/EditBundleAboutToStartTest.java
=> SSCS-8430 Edit Bundle Stitching fix

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-8536
https://tools.hmcts.net/jira/browse/SSCS-8537
=> SSCS-8536 and SSCS-8537 minor changes to decision notice content

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UcWriteFinalDecisionIt.java, src/test/resources/callback/writeFinalDecisionDescriptorUCNonLcwa.json, src/test/resources/callback/writeFinalDecisionDescriptorUCScenario.json
https://tools.hmcts.net/jira/browse/SSCS-8518
Adding UC integration tests
```
[ ] Yes
[x] No
```
=> Sscs 8518 uc integration tests

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/EsaDecisionNoticeFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/UcDecisionNoticeFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaTemplateContent.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcTemplateContent.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario2Test.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/scenarios/UcScenario2Test.java
=> Sscs 8528 8529 uc esa scenario 2 content change

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellantactioned/DeathOfAppellantActionedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellantactioned/DeathOfAppellantActionedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8472
=> SSCS-8472 Death of appellant actioned event

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/resendtogaps/ResendToGapsAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/resendtogaps/ResendToGapsAboutToSubmitHandlerTest.java
=> SSCS-8530: Robotics - send to robotics error

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8525
=> SSCS-8525 Appendix 12 document for DWP upload response event

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/resources/config/application-local.properties, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
SSCS-8449 - default all SYA cases to be created with digital = 'Yes'
=> SSCS-8449 - default all SYA cases to be created with digital = 'Yes'

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8115
=> SSCS-8115 Set confidential case flag

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8485
=> SSCS-8485 Remove confidential case flags on death of appellant

src/main/java/uk/gov/hmcts/reform/sscs/pdf/PdfWatermarker.java, src/test/java/uk/gov/hmcts/reform/sscs/pdf/PdfWatermarkerTest.java
=> SSCS-8572: Tribunals – Addition of the footer isn’t working as expected

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
Reverts hmcts/sscs-tribunals-case-api#1701
=> Revert "SSCS-8483 Refactor SubmitYourAppeal searches"

charts/sscs-tribunals-api/values.aat.template.yaml, charts/sscs-tribunals-api/values.preview.template.yaml, src/IntegrationTests/resources/config/application_it.properties, src/e2e/resources/config/application_e2e.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/main/resources/config/application-local.properties, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8431
=> Sscs 8431 remove feature flags

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8483
```
[ ] Yes
[ ] No
```
=> SSCS-8483 Refactor SubmitYourAppeal searches - fix

build.gradle, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCS-8573
```
[ ] Yes
[ ] No
```
=> SSCS-8573: White list scottish postcode for local testing

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8606
=> Sscs 8606 doa flag

src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java, src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SerializeJsonMessageManager.java, src/test/resources/tya/dwpRespondMyaForPaperHearingType.json
=> SSCS-8388: MYA – Hide the hearing information if the case is paper

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8597
=> Sscs 8597 phme bug

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/PipDecisionNoticeFunctionalTest.java
https://tools.hmcts.net/jira/browse/SSCS-8568
Fixing integration test
```
[ ] Yes
[x] No
```
=> Sscs 8568 lwca rename fix

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/PipDecisionNoticeFunctionalTest.java
https://tools.hmcts.net/jira/browse/SSCS-8568
Fixing test
```
[ ] Yes
[x] No
```
=> Sscs 8568 lwca rename2

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-8458
```
[ ] Yes
[x] No
```
=> sscs 8458 suppress kotlin cve

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwplapse/DwpLapseCaseHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwplapse/DwpLapseCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8598
=> SSCS-8598 Migrate DWP lapse event docs to dwp documents collection

audit.json
=> Add false positives for audit file

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java, src/test/resources/json/sya.json
https://tools.hmcts.net/jira/browse/SSCS-8458
```
[ ] Yes
[x] No
```
=> sscs 8458 fix logic

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/AppConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8600
=> Sscs 8600 migrate dwp upload response docs

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/BaseHandler.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/tya/GetAppealStatus.java, src/e2e/java/uk/gov/hmcts/reform/sscs/smoke/GetSavedCase.java
https://tools.hmcts.net/jira/browse/SSCS-8574
```
[ ] Yes
[ ] No
```
=> SSCS-8574:Look at Jenkins pipeline reliability

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateEditedBundleAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateEditedBundleAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8602
=> Sscs 8602 bundle dwp docs v2

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8681
=> SSCS-8681 Fix edited docs error

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8682
Bug fix
```
[ ] Yes
[x] No
```
=> sscs 8682 fix dynamic list edit

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8692
=> SSCS-8692 Handle empty appendix 12 doc

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateEditedBundleAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/AppConstants.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateEditedBundleAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8693
=> SSCS-8693 Remove DWP doc migration feature flag

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8698
=> SSCS-8698 Bundle config name fix

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8731
=> SSCS-8731 Fix response reviewed issue code bug for UC cases

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsSubmittedHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
=> SSCS 8257 Welsh Reinstatement Handling Judge

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/EvidenceUploadTest.java, src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8675
Changed the collection audio video go to
```
[ ] Yes
[x] No
```
=> sscs 8675 moved to audiovideo evidence

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToStartTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8732
Move documents around to support new collection
```
[ ] Yes
[x] No
```
=> sscs 8732 move docs to old position then put them back if updated

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java
added empty dwp office check for direction issued event
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8417](url)
=> added empty dwp office check for direction issued event

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CreateAndUpdateCaseInCcdTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToStartTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8735
=> SSCS-8735 Set DWP documents in response received event

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
=> SSCS-8746: Tribunals – Update to case data regex is still too strong

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DocumentUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/DocumentUtilTest.java
https://tools.hmcts.net/jira/browse/SSCS-8634
```
[ ] Yes
[ ] No
```
=> SSCS-8634: Upload A/V Evidence: CCD - Supplementary Response

gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
=> Fixed regex address validation

src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8673
see ticket
```
[ ] Yes
[ X] No
```
=> SSCS-8673 add a log message when uploading an additional evidence

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
=> Relax regex address validation

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java
SSCS-8734 : Exclude A/V evidence
=> SSCS-8734 : Exclude A/V evidence

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
Added process audio video evidence callbacks and tests:
Jira Ticket:[https://tools.hmcts.net/jira/browse/SSCS-8733](url)
=> Sscs 8733 process audio video evidence

build.gradle, dependency-check-suppressions.xml, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCS-8757
Local dev
```
[ ] Yes
[x] No
```
=> sscs 8757 local

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8739
```
[ ] Yes
[ ] No
```
=> SSCS-8739: Process Audio/Video Evidence Event - Send to Admin

build.gradle
Exclude batik
```
[ ] Yes
[x] No
```
=> exclude batik-all

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
SSCS-8740 - Process A/V Evidence: Send to Judge
=> SSCS-8740 - Process A/V Evidence: Send to Judge

build.gradle, dependency-check-suppressions.xml
=> Fixed tomcat vulnerabilities

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadfurtherevidence/UploadFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/bundle/BundleAudioVideoPdfService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadfurtherevidence/UploadFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bundle/BundleAudioVideoPdfServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java, src/test/resources/callback/createBundleCallbackWithAudioVideoEvidence.json
https://tools.hmcts.net/jira/browse/SSCS-8741
- Include audio video evidence in process audio video evidence event
- Change bundle to work with SSCS audio video documents and DWP audio video documents
- Minor refactoring
=> SSCS-8741 Include audio video evidence

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocReferralReason.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtowithdwp/AdminSendToWithDwpAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reviewphme/ReviewPhmeAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtowithdwp/AdminSendToWithDwpAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reviewphme/ReviewPhmeAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8697
=> SSCS-8697 Clear interloc fields for phme in admin send to dwp event

src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/SyaControllerTest.java, src/test/resources/json/sya_with_ccdId_null_benefit_type.json
https://tools.hmcts.net/jira/browse/SSCS-8807
Some  non personal logging to try and work out error on prod
```
[ ] Yes
[x] No
```
=> sscs-8807 log some data from bad request

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8829
=> SSCS-8829:Add Welsh flag - RIP1 Document

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/TyaEndpointsIt.java, src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentDownloadService.java, src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SerializeJsonMessageManager.java, src/test/resources/tya/audioVideoEvidenceCcd.json, src/test/resources/tya/audioVideoEvidenceMya.json
https://tools.hmcts.net/jira/browse/SSCS-8742
=> SSCS-8742:View Audio/Video Evidence Link - MYA

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CreateWelshNoticeIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createwelshnotice/CreateWelshNoticeAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createwelshnotice/CreateWelshNoticeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createwelshnotice/CreateWelshNoticeAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createwelshnotice/CreateWelshNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/resources/callback/createWelshNoticeDirection.json
SSCS-8752 - Issue Directions Notice - Send to all Parties
New event processAudioVideoWelsh, that will be triggered by the code when it sees a new documentType of audioVideoNotice
Ensures translationRequired is set for the audioVideoNotice
=> SSCS-8752 - Issue Directions Notice - Send to all Parties

build.gradle
updated common so DLA code gets set
Jira ticket: [https://tools.hmcts.net/jira/browse/SSCS-8835](url)
=> Sscs 8835 set dla benefit code

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CreateBundleIt.java, src/IntegrationTests/resources/config/application_it.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java, src/test/resources/callback/createBundleCallbackWithEditedDocuments.json, src/test/resources/callback/createWelshBundleCallback.json, src/test/resources/callback/createWelshBundleCallbackWithEditedDocuments.json
https://tools.hmcts.net/jira/browse/SSCS-8851
=> SSCS-8851 Multi bundle config

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadfurtherevidence/UploadFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadfurtherevidence/UploadFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8874
=> Sscs 8874 audio video interloc review state

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/e2e/resources/handlers/processaudiovideo/processAudioVideoEvidenceAboutToStartCallback.json, src/e2e/resources/handlers/processaudiovideo/processAudioVideoEvidenceAboutToSubmitCallback.json
added about to start and submit functional test for processAudioVideoEvidence event
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8883](url)
=> Sscs 8883 audio video evidence functional test

build.gradle
SSCS-8876 - MYA – When uploading documents the evidenceHandled flag is not getting populated
=> SSCS-8876 - MYA – When uploading documents the evidenceHandled flag is not getting populated

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
SSCS-8866 - CCD UI – When clearing the post code, the case becomes Scottish
=> SSCS-8866 - CCD UI – When clearing the post code, the case becomes Scottish

src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DateTimeUtils.java, src/test/resources/tya/adjournmentNoticeCaseMya.json, src/test/resources/tya/dormantMya.json, src/test/resources/tya/dwpRespondMya.json, src/test/resources/tya/dwpRespondMyaForPaperHearingType.json, src/test/resources/tya/dwpRespondOverdue-caseId.json, src/test/resources/tya/finalDecisionCaseMya.json, src/test/resources/tya/hearingAdjournedMya.json, src/test/resources/tya/hearingMya.json, src/test/resources/tya/hearingPaperMya.json, src/test/resources/tya/notListableMya.json
https://tools.hmcts.net/jira/browse/SSCS-8872
changed time to local
```
[ ] Yes
[x] No
```
=> sscs 8872 don't utc time

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java
edited log before setting previousState
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8717](url)
=> edited log before setting previousState

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8861
=> SSCS-8861 Upload welsh DWP RIP 1 document

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addnote/AddNoteAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addnote/AddNoteAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8770
Add note and put it into collection
```
[ ] Yes
[x] No
```
=> sscs 8870 add note handler

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/FooterService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/uc/UcIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/FooterServiceTest.java
SSCS-8857- No Welsh translation for final decision notice
=> SSCS-8857- No Welsh translation for final decision notice

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-8892
=> SSCS-8892 Carers Allowance benefit code

src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/NoticeIssuedTemplateBody.java
https://tools.hmcts.net/jira/browse/SSCS-8975
=> SSCS-8975: Scottish logo not appearing on decision noticie

build.gradle, gradle.properties
- Increase gradle timeouts for cases where we are pulling a package for the first time from jitpack.io
=> DTSPO-1792 increase gradle timeouts

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8970
=> SSCS-8970 Clear empty audio video list

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DwpDocumentService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
=> SSCS-9007: CCD UI – Response reviewed – documents are being cleared

build.gradle, dependency-check-suppressions.xml
=> SSCS-9046 - fix DC failures

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/MidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/MidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9011
https://tools.hmcts.net/jira/browse/SSCS-9013
=> SSCS-9011, 9013 Admit audio evidence and validate due date

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/resources/callback/uploaddocument/uploadAudioVideoDocumentFECallback.json
https://tools.hmcts.net/jira/browse/SSCS-9017
=> SSCS-9017 Default audio video empty file name

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8973
Changed so one bundle when rejected
```
[ ] Yes
[x] No
```
=> sscs 8973 remove edited bundle for phme rejected

src/main/java/uk/gov/hmcts/reform/sscs/controller/EvidenceManagementController.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/EvidenceManagementControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7602
Exception logged during .docx .rtf evidence upload. Enables better tracking
```
[ ] Yes
[x ] No
```
=> SSCS-7602-Exception logged during .docx .rtf evidence upload

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
=> SSCS-8790 Set DWP Offices for Carers Allowance

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocReferralReason.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadfurtherevidence/UploadFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/supplementaryresponse/SupplementaryResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadfurtherevidence/UploadFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9008
=> SSCS-9008: A/V Evidence: Set Interlocutory Referral Reason

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CreateBundleIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9002
=> SSCS-9002 Remove unedited bundle config

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-8766
=> SSCS-8766 Attendance Allowance benefit type

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/OriginalSenderItemList.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
=> SSCS-8995 - HMCTS evidence

src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionDraft.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingOptions.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingOptionsFaceToFace.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingOptionsTelephone.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingOptionsVideo.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingSelectOptions.java, src/main/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraft.java, src/test/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraftTest.java
=> SSCS-8890 Add missing Hearing Sub Type to draft response

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9015
```
[ ] Yes
[ ] No
```
=> SSCS-9015:Investigate how to play mp3 and mp4 videos in browser from CCD 

dependency-check-suppressions.xml
=> dependency-check-suppressions

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/pdf/PdfState.java, src/main/java/uk/gov/hmcts/reform/sscs/service/AbstractFooterService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/domain/wrapper/pdf/PdfStateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/FooterServiceTest.java
=> minor refactoring

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/pdf/PdfState.java, src/main/java/uk/gov/hmcts/reform/sscs/service/AbstractFooterService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/domain/wrapper/pdf/PdfStateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/FooterServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8967
```
[ ] Yes
[ x] No
```
=> SSCS-8967:Handle error for unreadable and encrypted PDF for Action further evidence

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8998
```
[ ] Yes
[ ] No
```
=> SSCS-8998:Send to interloc TCW – adding docs to bundle

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtowithdwp/AdminSendToWithDwpAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DateTimeUtils.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminsendtowithdwp/AdminSendToWithDwpAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8870
=> SSCS-8870:CCD UI – Implement DWP due date field

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocReferralReason.java
https://tools.hmcts.net/jira/browse/SSCS-9160
Missing label of interloc reason
```
[ ] Yes
[x] No
```
=> sscs 8160 added missing interloc reason

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9117
=> SSCS-9117 Reverse some flags set during review confidentiality handler

audit.json
Ticket raised here https://tools.hmcts.net/jira/browse/SSCS-9196 to fix the warnings
```
[ ] Yes
[ ] No
```
=> Suppress warning

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/MidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DateTimeUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/MidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/DateTimeUtilsTest.java
SSCS-9094 - migrate annotation validation
related PR: https://github.com/hmcts/sscs-common/pull/838
=> SSCS-9094 - migrate annotation validation

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8906
=> SSCS-8906 Bereavement benefit DWP mappings

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validappeal/ValidateAppealAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validappeal/ValidateAppealAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9184
```
[ ] Yes
[ x] No
```
=> SSCS-9184:Validate appeal Dwp regional centre

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/HmctsResponseReviewedIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToStartTest.java
SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event
=> SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
added null check for benefit type and nino when filtering linked cases:
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9192](url)
=> added null check for benefit type and nino when filtering linked cases

build.gradle
=> SSCS-9122 Upgrade Common

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/updatewelshpreference/UpdateWelshPreferenceAboutToSubmitHandlerFunctionalTest.java, src/e2e/resources/handlers/updatewelshpreference/updateWelshPreferenceAboutToSubmitCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addnote/AddNoteAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatewelshpreference/UpdateWelshPreferenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatewelshpreference/UpdateWelshPreferenceAboutToSubmitHandlerTest.java
add note when changing welsh preference if interloc review state is in welsh translations state
Jira ticket: [https://tools.hmcts.net/jira/browse/SSCS-9092](url)
=> Sscs 9092 add note when changing welsh preference

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/EvidenceUploadTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9181
=> Sscs 9181 admit av evidence with statement

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/EvidenceUploadTest.java, src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9221
=> SSCS-9221 Upload AV statement to audio video collection

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/TyaEndpointsIt.java, src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentDownloadService.java, src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DocumentDownloadServiceTest.java, src/test/resources/tya/adjournmentNoticeCaseMya.json, src/test/resources/tya/audioVideoEvidenceMya.json, src/test/resources/tya/finalDecisionCaseMya.json
https://tools.hmcts.net/jira/browse/SSCS-9288
Change full url to an id for WAF
```
[ ] Yes
[x] No
```
=> SSCS-9288 change url to an id

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java, src/e2e/resources/handlers/uploadhearingrecording/hearingsAttendedCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DateTimeUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/DateTimeUtilsTest.java
https://tools.hmcts.net/jira/browse/SSCS-9222
```
[ ] Yes
[ x] No
```
=> SSCS-9222: Select hearing for Upload hearing recording event

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/generatecoversheet/GenerateCoversheetAboutToStartHandler.java
SSCS-9331-Fortify Issues part 2
=> SSCS-9331-Fortify Issues part 2

audit.json
=> Suppres low alert

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addnote/AddNoteAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addnote/AddNoteAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9329
=> SSCS-9329 Response reviewed check interloc reason is none bug fix

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/audiovideo/AudioVideoState.java, src/main/java/uk/gov/hmcts/reform/sscs/util/AudioVideoEvidenceUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9231
Fields added and validated for upload recording hearing mid event
```
[ ] Yes
[ x] No
```
=> SSCS-9231: Upload hearing recording page

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9303
=> SSCS-9303 Do not show error if further info missing as cannot be empty

audit.json
=> Suppress low warnings

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandlerBase.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/gen/GenWriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipWriteFinalDecisionMidEventValidationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcWriteFinalDecisionMidEventValidationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/uc/UcWriteFinalDecisionMidEventValidationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9317
=> SSCS-9317 Summary of outcome getting cleared when editing from summary

src/main/java/uk/gov/hmcts/reform/sscs/service/DocumentDownloadService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/DocumentDownloadServiceTest.java, src/test/resources/tya/finalDecisionCaseMya.json
https://tools.hmcts.net/jira/browse/SSCS-9322
handle sya creating documents
```
[ ] Yes
[x] No
```
=> SSCS-9322-handle old url checking

build.gradle
=> resolve CVE-2021-30468

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/ProcessAudioVideoIt.java, src/test/resources/callback/processAudioVideoEvidenceCallback.json, src/test/resources/callback/processAudioVideoEvidenceWithDueDateCallback.json
https://tools.hmcts.net/jira/browse/SSCS-9327
=> SSCS-9327 Process AV evidence integration test

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
SSCS-9340 - CCD UI – Action manually has documents sent to bulk print
=> SSCS-9340 - CCD UI – Action manually has documents sent to bulk print

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9336
=> SSCS-9336 NPE fix for empty document names

src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingOptionsFaceToFace.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingOptionsTelephone.java, src/main/java/uk/gov/hmcts/reform/sscs/model/draft/SessionHearingOptionsVideo.java, src/main/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraft.java, src/test/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraftTest.java
https://tools.hmcts.net/jira/browse/SSCS-9105
Send true and false out to javascript rather than yes, no or undefined
```
[ ] Yes
[x] No
```
=> sscs 9105 return booleans rather than Yes/No

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9330
=> SSCS-9330 Fix directions due date error fix

dependency-check-suppressions.xml
=> Suppress for one more month

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/uploadhearingrecording/UploadHearingRecordingAboutToSubmitHandlerTest.java, src/e2e/resources/handlers/uploadhearingrecording/hearingRecordingsCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/HearingTypeForRecording.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9233
```
[ ] Yes
[x ] No
```
=> SSCS-9233: Upload hearing recordings submit event

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/PipWriteFinalDecisionIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipTemplateContent.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioEnhancedRateEnhancedRateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioEnhancedRateStandardRateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioNoAwardEnhancedRateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioNoAwardStandardRateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioNotConsideredEnhancedRateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioNotConsideredStandardRateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioStandardRateEnhancedRateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/scenarios/PipScenarioStandardRateStandardRateTest.java
https://tools.hmcts.net/jira/browse/SSCS-9316
=> SSCS-9316 Decision notice formatting fix

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/admin/RestoreCasesService2.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java
Allow social fund
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9061](url)
=> Sscs 9061 allow social fund

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/requesthearingrecording/RequestHearingRecordingAboutToStartHandlerFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/requesthearingrecording/RequestHearingRecordingAboutToSubmitHandlerFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requesthearingrecording/RequestHearingRecordingAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requesthearingrecording/RequestHearingRecordingAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestinfo/RequestInfoIncompleteApplicationAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/DocumentType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requesthearingrecording/RequestHearingRecordingAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requesthearingrecording/RequestHearingRecordingAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsUtilTest.java
https://tools.hmcts.net/jira/browse/SSCS-9228
=> SSCS-9228 Upload document FE hearing recording request

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/DwpUploadResponseIt.java, src/test/resources/callback/dwpUploadResponse.json, src/test/resources/callback/dwpUploadResponseError.json, src/test/resources/callback/dwpUploadResponsePhme.json
upload response integration tests
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9363](url)
=> Sscs 9363 upload response integration tests

audit.json
=> update * to sscs

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9213
=> SSCS-9213 Add other benefit types

charts/sscs-tribunals-api/values.preview.template.yaml
Fix PR's due to changes in chart from this [commit](https://github.com/hmcts/ccd-data-store-api/commit/7aaea598ec77a756df825631d157ab41080b32b1).
=> Fix PR's due to changes in chart

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9450
=> Sscs 9450 regional centre rfe

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9459
=> SSCS-9459 Update income support rfe mapping

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AbstractEventIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UploadDocumentFurtherEvidenceIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UploadFurtherEvidenceIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/helper/IntegrationTestHelper.java
SSCS-9387 - Add integration test for Upload document FE
=> SSCS-9387 - Add integration test for Upload document FE

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/SupplementaryResponseIt.java
https://tools.hmcts.net/jira/browse/SSCS-9385
added integration tests for Supplementary Response Event
```
[ ] Yes
[ x] No
```
=> Sscs 9385 add integration tests sup response

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, src/main/resources/config/application-local.properties, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCS-9381
The changes are in this PR but the same are implemented on nightly* branch
```
[ ] Yes
[ x] No
```
=> SSCS-9381: Fortify scan for nightly build

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confidentialityrequest/ReviewConfidentialityRequestAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9481
=> SSCS-9481 isProgressingViaGaps enhanced confidentiality feature flag

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/TribunalsCaseApiApplication.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/MidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/elementsdisputed/ElementsDisputedMidEventValidationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/uc/UcIssueFinalDecisionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandlerTestBase.java
=> fix for CVE-2021-28170

src/main/java/uk/gov/hmcts/reform/sscs/service/converter/ConvertSscsCaseDataIntoSessionDraft.java
https://tools.hmcts.net/jira/browse/SSCS-9477
Return issuing office for non pip
```
[ ] Yes
[x] No
```
=> sscs 9477 return office for all types other than pip

audit.json
=> ignore low warnings

dependency-check-suppressions.xml, src/contractTest/java/uk/gov/hmcts/reform/sscs/ccd/idam/IdamApiConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/sscs/ccd/idam/IdamConsumerTestBase.java, src/contractTest/resources/config/application_contract.properties
https://tools.hmcts.net/jira/browse/SSCS-9421
```
[ ] Yes
[ x] No
```
=> SSCS-9421: IDAM Consumer PACT test

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java
Reverts hmcts/sscs-tribunals-case-api#2271
=> Revert "Sscs 9433 postponement req"

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9558
```
[ ] Yes
[ x] No
```
=> SSCS-9558:Warning for same letter in bundle

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionposteponementrequest/ActionPostponementRequestTest.java, src/e2e/resources/handlers/actionpostponementrequest/actionPostponementRequestAboutToSubmitCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9438
Action Postponement Request Event - Send to Judge
```
[ ] Yes
[ x] No
```
=> Sscs 9438 postponement send to judge

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionposteponementrequest/ActionPostponementRequestTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9439
Action Postponement Request Event - Grant Postponement
```
[ ] Yes
[ x] No
```
=> Sscs 9439 action postponement request event   grant postponement

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9440
Action Postponement Request Event - Refuse
```
[ ] Yes
[ x] No
```
=> Sscs 9440 action postponement request event refuse

build.gradle, src/IntegrationTests/resources/config/application_it.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocMidEventHandler.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9436
=> Sscs 9436 postponements feature flag

src/main/java/uk/gov/hmcts/reform/sscs/controller/CreateCaseController.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CreateCaseControllerTest.java
SSCS-9584 - Update ccd-e2e test framework to generate test data with random NINO, MRN-Date
=> SSCS-9584 - Update ccd-e2e test framework to generate test data with random NINO, MRN-Date

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCS-9560
=> SSCS-9560 Update broken AV doc link in bundle

audit.json
ignore security scan issues
Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9611](url)
=> SSCS-9611-ignore-security-scan-issues

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/processhearingrecordingrequest/ActionHearingRecordingRequestAboutToSubmitHandlerFunctionalTest.java, src/e2e/resources/handlers/actionhearingrecordingrequest/actionHearingRecordingRequestAboutToSubmitCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/actionhearingrecordingrequest/ActionHearingRecordingRequestService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/processhearingrecordingrequest/ActionHearingRecordingRequestServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9561
Change Event Name from 'Process hearing recording' to 'Action hearing recording req'
```
[ x] Yes
[ ] No
```
=> SSCS-9561- change event name

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/adjourncase/AdjournCaseService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/adjourncase/AdjournCaseServiceTest.java
SSCS-9580 -  User can't get past 'Direction due date' page within 'Write Adjournment notice' event
=> SSCS-9580 -  User can't get past 'Direction due date' page within 'Write Adjournment notice' event

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AbstractEventIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/SupplementaryResponseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/BundleCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/AssociatedCaseLinkHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/canceltranslations/CancelTranslationsSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createwelshnotice/CreateWelshNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createwelshnotice/CreateWelshNoticeSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpdirectionresponse/DwpDirectionResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwprequesttimeextension/DwpRequestTimeExtensionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/markdocsfortranslation/MarkDocumentsForTranslationAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatewelshpreference/UpdateWelshPreferenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadwelshdocument/UploadWelshDocumentsSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdCallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9429
=> SSCS-9429 Deserialize case type id for secure docstore bundle service

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/PostponementRequestService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/PostponementRequestServiceTest.java, src/test/resources/callback/adminSendToInterlocSelectedWhoToReviewCasePostponementRequest.json, src/test/resources/callback/validSendToInterlocSelectedWhoToReviewCase.json, src/test/resources/callback/validSendToInterlocSelectedWhoToReviewCasePostponementRequest.json
SSCS-9678 - Send to Interloc Event Warning Message
=> SSCS-9678 - Send to Interloc Event Warning Message

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml
Turn on docstore in AAT
```
[ ] Yes
[x] No
```
=> Turn on docstore in AAT

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml
=> Fix chart issue

build.gradle
removing errors from logs
```
[ ] Yes
[ ] No
```
=> Release secure docstore logging

src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/model/tya/HearingRecording.java, src/main/java/uk/gov/hmcts/reform/sscs/service/citizenrequest/CitizenRequestService.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DocumentUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/citizenrequest/CitizenRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/DocumentUtilTest.java, src/test/resources/tya/hearingRecordingMya.json
https://tools.hmcts.net/jira/browse/SSCS-9814
```
[ ] Yes
[ ] No
```
=> SSCS-9814 MYA Demo - Audio files don't playback in MYA application

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginService.java, src/main/java/uk/gov/hmcts/reform/sscs/util/PostcodeUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/PostcodeUtilTest.java
SSCS-9801 - MYA other party login
=> SSCS-9801 - MYA other party login

build.gradle
=> Revert SSCS-9777: Tribunals / Common – Change the document ordering

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/PartiesOnCaseUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9846
=> Sscs 9846 remove button validation

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AbstractEventIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/ActionHearingRecordingIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/helper/IntegrationTestHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandlerTest.java
SSCS-9847 - Action hearing recording Integration tests
=> SSCS-9847 - Action hearing recording Integration tests

build.gradle
=> SSCS-9777: Tribunals / Common – Change the document ordering

build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9748
=> SSCS-9748 Add other party hearing preferences document type

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/NoticeIssuedTemplateBody.java
https://tools.hmcts.net/jira/browse/SSCS-9833
Child Support - Notifications: Delete NINO
```
[ ] Yes
[ x] No
```
=> SSCS-9833 documents with NINO hidden for child support

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AbstractEventIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/ActionHearingRecordingIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/helper/IntegrationTestHelper.java, src/e2e/resources/handlers/actionhearingrecordingrequest/actionHearingRecordingRequestAboutToSubmitCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/actionhearingrecordingrequest/ActionHearingRecordingRequestService.java, src/main/java/uk/gov/hmcts/reform/sscs/util/PartiesOnCaseUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionhearingrecordingrequest/ActionHearingRecordingRequestMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/processhearingrecordingrequest/ActionHearingRecordingRequestServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9787
=> SSCS-9787 Update hearing recording requests for other parties

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/resources/callback/actionFurtherEvidenceWithInterlocOptionCallback.json, src/test/resources/callback/appealDormantCallback.json
https://tools.hmcts.net/jira/browse/SSCS-9776
```
[ ] Yes
[x ] No
```
=> SSCS-9776:Action further evidence warning message

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9767
```
[ ] Yes
[x ] No
```
=> SSCS-9767: Add warning for hearing option during update to case data

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/subscriptionupdated/SubscriptionUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginService.java, src/main/java/uk/gov/hmcts/reform/sscs/util/OtherPartyDataUtil.java, src/main/java/uk/gov/hmcts/reform/sscs/util/PostcodeUtil.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/subscriptionupdated/SubscriptionUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/OtherPartyDataUtilTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/PostcodeUtilTest.java, src/test/resources/callback/actionFurtherEvidenceCallback.json
https://tools.hmcts.net/jira/browse/SSCS-9735
```
[ ] Yes
[x] No
```
=> Sscs 9735 2 subscription other party

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9925
```
[ ] Yes
[ ] No
```
=> SSCS-9925: SSCS2 Form - Upload Response-: Edited and Unedited Response

build.gradle, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CreateAndUpdateCaseInCcdTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/resources/sya/allDetailsFromDraftCcd.json, src/test/resources/sya/allDetailsFromDraftNoMrnDateCcd.json, src/test/resources/sya/allDetailsFromDraftWithInterlocCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdChildSupport.json, src/test/resources/sya/allDetailsNonSaveAndReturnNoMrnDateCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnWithInterlocCcd.json
https://tools.hmcts.net/jira/browse/SSCS-9882
caseName field for SYA
```
[ ] Yes
[x] No
```
=> sscs 9882 set caseName for SYA

dependency-check-suppressions.xml
=> suppress jakarta.el

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processreasonableadjustment/ProcessReasonableAdjustmentAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processreasonableadjustment/ProcessReasonableAdjustmentAboutToSubmitHandlerTest.java
SSCS-9927 - Process Reasonable Adjustments for Other Parties
=> SSCS-9927 - Process Reasonable Adjustments

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9893
Errors instead of warnings
```
[ ] Yes
[x] No
```
=> sscs 9893 changed to error

build.gradle, charts/sscs-tribunals-api/values.yaml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CaseUpdatedIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/ReviewPhmeRequestIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/client/RefDataClientIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/IntegrationTests/resources/config/application_it.properties, src/IntegrationTests/resources/config/application_refdata_it.properties, src/main/java/uk/gov/hmcts/reform/sscs/TribunalsCaseApiApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/reviewphme/ReviewPhmeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
=> SSCS-9903: Location data – Populate location data on creation SYA and case update

charts/sscs-tribunals-api/Chart.yaml
Reverts hmcts/sscs-tribunals-case-api#2545
=> Revert "Update Helm release redis to v15.7.6"

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9961
=> SSCS-9961 Set HMCTS Service Id in supplementary data

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/resources/sya/allDetailsFromDraftCcd.json, src/test/resources/sya/allDetailsFromDraftNoMrnDateCcd.json, src/test/resources/sya/allDetailsFromDraftWithInterlocCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdChildSupport.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdSscs5.json, src/test/resources/sya/allDetailsNonSaveAndReturnNoMrnDateCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnWithInterlocCcd.json
https://tools.hmcts.net/jira/browse/SSCS-9945
New fields for WA
```
[ ] Yes
[X] No
```
=> Sscs 9945 wa fields

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java
https://tools.hmcts.net/jira/browse/SSCS-9945
Tests should pass now released to prod
```
[ ] Yes
[x] No
```
=> sscs 9945 remove ignore from tests

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9841
=> SSCS-9841 Robotics for sscs5

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UpdateOtherPartyDataIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UpdateSscs5OtherPartyDataIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/OtherPartyDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandlerTest.java, src/test/resources/callback/updateOtherPartySscs5Callback.json
https://tools.hmcts.net/jira/browse/SSCS-10004
```
[ ] Yes
[ x] No
```
=> SSCS-10004:Update hearing type for non SSCS1 case

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CaseUpdatedIt.java, src/test/java/uk/gov/hmcts/reform/sscs/service/RestoreCasesService2Test.java
=> SSCS-9902: Location data – Update airlookup to v15

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-9902
```
[ ] Yes
[x] No
```
=> SSCS-9902 Increase Jakarta CVE supperesion by one month.

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
https://tools.hmcts.net/jira/browse/SSCS-10070
Change data in 'caseAccessCategory' field from human readable to camelcase
```
[ ] Yes
[ ] No
```
=> update test case for sscs-10070

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10130
```
[ ] Yes
[X] No
```
=> surpress dependencies

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/resources/sya/allDetailsFromDraftCcd.json, src/test/resources/sya/allDetailsFromDraftNoMrnDateCcd.json, src/test/resources/sya/allDetailsFromDraftWithInterlocCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdChildSupport.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdSscs5.json, src/test/resources/sya/allDetailsNonSaveAndReturnNoMrnDateCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnWithInterlocCcd.json
https://tools.hmcts.net/jira/browse/SSCS-10070
Change data in 'caseAccessCategory' field from human readable to camelcase
```
[ ] Yes
[ ] No
```
=> SSCS - 10070 - Change data in 'caseAccessCategory' field 

build.gradle, dependency-check-suppressions.xml
Pipelines causing security issues due to springboot security having vulnerability
```
[ ] Yes
[X] No
```
=> Upgrade secuirty dependency

build.gradle
=> updating log4j to version 2.17

build.gradle
rolling back change in common for supp data
```
[ ] Yes
[x] No
```
=> rollback change

build.gradle
=> Update build.gradle p2 fix - will back out later

build.gradle
=> Update build.gradle - revert p2-deploy-fix

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
This reverts commit 6536a7076625f4cf74a629bbbd0826a25d7f0658.
Remove evidence changes are reverted back
```
[X] Yes
[ ] No
```
=> Revert "Sscs 10018 process audio video (#2596)"

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
Resole RPC and Venue based on provided postcode.
https://tools.hmcts.net/jira/browse/SSCS-9896
```
[ ] Yes
[x] No
```
=> Sscs 9896 use appointee post code to update rpc processing venue (SYA)

audit.json
=> add more suppressions

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/createbundle/CreateBundleAboutToSubmitHandlerFunctionalTest.java
https://tools.hmcts.net/jira/browse/SSCS-10147
Updating test as when i merge in em orch changes the functional tests will start failing
```
[ ] Yes
[x] No
```
=> sscs 10147 change folder name in test

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9880
```
[ ] Yes
[ x] No
```
=> SSCS-9880:Check valid benefit for SSCS5 during Upload case data

charts/sscs-tribunals-api/Chart.yaml
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/SSCS-10236
```
[ ] Yes
[X] No
```
=> SSCS-10236 Updating helm chart version

charts/sscs-tribunals-api/Chart.yaml
https://tools.hmcts.net/jira/browse/SSCS-10236
```
[ ] Yes
[X] No
```
=> SSCS-10236: updating helm chart versions

src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9896
```
[ ] Yes
[x] No
```
=> SSCS-9896 Use appointee postcode to update rpc processing venue.

dependency-check-suppressions.xml
=> SSCS-10280: CVE suppression

dependency-check-suppressions.xml, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-10297
```
[ ] Yes
[X] No
```
=> SSCS-10297: suppressing dependencies

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controller/CitizenRequestControllerIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controller/SubscriptionsControllerIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/postcode/PostCodeEndpointsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/SubscriptionEndPointsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/TyaEndpointsIt.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwplapse/DwpLapseCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/pdf/PdfWatermarkerTest.java
https://tools.hmcts.net/jira/browse/SSCS-10265
```
[ ] Yes
[x] No
```
=> SSCS-10265 Fixed Tests

infrastructure/resource-group.tf, infrastructure/service-bus.tf
=> SSCS-10220 Fix resource group.

dependency-check-suppressions.xml
=> SSCS-10376 Fix Suppressions

audit.json
=> suppress security fix

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/HearingHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-10387
```
[ ] Yes
[x] No
```
=> SSCS-10387 Update Commons

Jenkinsfile_CNP, build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10440
```
[ ] Yes
[X] No
```
=> Update sprintboot core

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SscsMyaBackendRequests.java
=> SSCS-1223 Remove jcenter.

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SscsMyaBackendRequests.java
https://tools.hmcts.net/jira/browse/SSCS-10479
```
[ ] Yes
[ ] No
```
=> SSCS-10479 Fix dependencies after jCenter removal.

build.gradle, src/IntegrationTests/resources/config/application_it.properties, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/AddedDocumentsUtil.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SyaServiceHelper.java
https://tools.hmcts.net/jira/browse/SSCS-10490
- changed CaseUpdatedAboutToSubmitHandler to use case access management feature flag
- changed SubmitYourAppealToCcdCaseDataDeserializer to also use cam feature flag
- associated model and test changes
- code tidy
```
[ ] Yes
[ x ] No
```
=> SSCS-10490 change access management feature flag

charts/sscs-tribunals-api/values.aat.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-10490
added expected feature flag env vars for functional tests
**Does this PR introduce a breaking change?**
```
[ ] Yes
[ x ] No
```
=> SSCS-10490 added expected ff env vars for functional tests

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.aat.template.yaml, charts/sscs-tribunals-api/values.preview.template.yaml, charts/sscs-tribunals-api/values.yaml, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCS-10490
fixed typo in feature flag
**Does this PR introduce a breaking change?**
```
[ ] Yes
[ x ] No
```
=> SSCS-10490 fixed typo in feature flag

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10552
```
[ ] Yes
[X] No
```
=> SSCS-10552: Upgrading Tomcat

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10555
```
[ ] Yes
[X] No
```
=> SSCS-10555: Upgrading Spring

infrastructure/service-bus.tf
https://tools.hmcts.net/jira/browse/SSCS-10220
Enable Queue sessions requirement.
```
[ ] Yes
[X] No
```
=> SSCS-10220-enable-queue-sessions2

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10619
Renew suppressions
```
[ ] Yes
[ x] No
```
=> SSCS-10619-Update-Suppressions: Renew supression time

infrastructure/service-bus.tf, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/AppConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToStartHandlerTest.java
SSCS-10350 - Merging PR changes from https://github.com/hmcts/sscs-tribunals-case-api/pull/2742
=> Sscs 10350

charts/sscs-tribunals-api/Chart.yaml
N/A
Update chart version
```
[ ] Yes
[x] No
```
=> build: update chart version

charts/sscs-tribunals-api/Chart.yaml
=> Bump redis chart 15.7.6

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10445
```
[ ] Yes
[x] No
```
=> SSCS-10445 Commons Bump

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10138
Update tribunals with new sscs-commons version
```
[ ] Yes
[ x] No
```
=> Update tribunals with new sscs-commons version

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/model/AppConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToStartHandlerTest.java
Creating latest branch from master and pushing my changes. 
https://github.com/hmcts/sscs-tribunals-case-api/pull/2742 - Old PR is rebased with demo branch so better to do it in a clean way with fresh PR.
=> Creating latest branch from master and pushing my changes

build.gradle
=> SSCS-10245 RC bump

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dormant/DormantEventsAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dormant/DormantEventsAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-10641
Amend cancel hearings reason for Admin-Send Dormant event
```
[ ] Yes
[x] No
```
=> feat: amend cancel reason for event ADMIN_SEND_TO_DORMANT_APPEAL_STATE

infrastructure/main.tf
=> Sscs 10668 readd prev config

build.gradle
=> SSCS-10559 Commons bump 4.12.0

build.gradle, src/test/resources/callback/uploaddocument/expectedUploadDocumentFECallbackResponse.json, src/test/resources/callback/withdrawnappeals/adminAppealWithdrawnExpectedCaseData.json, src/test/resources/callback/withdrawnappeals/dwpActionWithdrawalExpectedCaseData.json
https://tools.hmcts.net/jira/browse/SSCS-10620
```
[ ] Yes
[x] No
```
=> SSCS-10620 Adding new fields to test Jsons

build.gradle, src/test/resources/callback/uploaddocument/expectedUploadDocumentFECallbackResponse.json, src/test/resources/callback/uploaddocument/uploadDocumentFECallback.json, src/test/resources/callback/withdrawnappeals/adminAppealWithdrawnExpectedCaseData.json, src/test/resources/callback/withdrawnappeals/dwpActionWithdrawalExpectedCaseData.json, src/test/resources/sya/allDetailsFromDraftCcd.json, src/test/resources/sya/allDetailsFromDraftNoMrnDateCcd.json, src/test/resources/sya/allDetailsFromDraftWithInterlocCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdChildSupport.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdSscs5.json, src/test/resources/sya/allDetailsNonSaveAndReturnNoMrnDateCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnWithInterlocCcd.json
https://tools.hmcts.net/jira/browse/SSCS-10242
```
[ ] Yes
[x] No
```
=> Sscs 10242 commons bump

infrastructure/service-bus.tf
=> SSCS-10651 Re-enable sessions. Will be disabled for the re

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.yaml
=> SSCS-10703 Add base preview config.

Jenkinsfile_CNP
=> SSCS-10742 Temporarily remove perftest sync

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10706
Turn Cardiff to LA 
```
[ ] Yes
[x] No
```
=> List Assist Cardiff Switch Commons Bumb

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java
=> SSCS-10334 Remove CaseAccessCategory ignore.

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10746
```
[ ] Yes
[ ] No
```
=> SSCS-10746-cve-suppressionSSCS-10746 s

audit.json, charts/sscs-tribunals-api/Chart.yaml
sscsBaseChartUpdate-Java401
```
[ ] Yes
[ ] No
```
=> sscsBaseChartUpdate-Java401

charts/sscs-tribunals-api/Chart.yaml
sscs servicebus update
```
[ ] Yes
[ ] No
```
=> sscs servicebus update

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java
https://tools.hmcts.net/jira/browse/SSCS-10739
```
[ ] Yes
[x] No
```
=> SSCS-10739 List Case After Postponement

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java
Reverts hmcts/sscs-tribunals-case-api#2870
=> Revert "SSCS-10739 List Case After Postponement"

audit.json, dependency-check-suppressions.xml
=> suppress zap false positives

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/resendtogaps/ResendToGapsAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/resendtogaps/ResendToGapsAboutToSubmitHandlerTest.java
=> SSCS-10750 Do not send existing GAPs cases to list assist.

charts/sscs-tribunals-api/Chart.yaml
=> Bump ccd chart 8.0.17

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
=> Add elastic name override

src/cftlib/java/uk/gov/hmcts/reform/sscs/CftlibConfig.java
=> SSCS-10315 Fix roles.

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10773
Commons bump
```
[ ] Yes
[ x] No
```
=> SSCS-10773: commons version bump

build.gradle
=> SSCS-10315 Add document environment variables.

src/cftlib/java/uk/gov/hmcts/reform/sscs/CftlibConfig.java
=> Create dedicated test superuser.

src/cftlib/java/uk/gov/hmcts/reform/sscs/CftlibConfig.java
=> Restore cftlib roles

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10857
```
[ ] Yes
[ ] No
```
=> SSCS-10857 Add new environment variables, bump cft lib.

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CaseUpdatedIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/client/RefDataClientIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10841
```
[ ] Yes
[ ] No
```
=> SSCS-10841 Use epims ID to resolve court venue.

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CaseUpdatedIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/client/RefDataClientIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/sya/SyaEndpointsIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
Reverts hmcts/sscs-tribunals-case-api#2899
=> Revert "SSCS-10841 Use epims ID to resolve court venue."

build.gradle, dependency-check-suppressions.xml
Updating dependencies
```
[ ] Yes
[x ] No
```
=> SSCS-update-dependencies: rising springframework version

.gitignore, build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.preview.template.yaml, dependency-check-suppressions.xml, src/e2e/resources/handlers/actionpostponementrequest/actionPostponementRequestAboutToSubmitCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java, src/test/resources/callback/uploaddocument/expectedUploadDocumentFECallbackResponse.json, src/test/resources/callback/withdrawnappeals/adminAppealWithdrawnExpectedCaseData.json, src/test/resources/callback/withdrawnappeals/dwpActionWithdrawalExpectedCaseData.json
https://tools.hmcts.net/jira/browse/SSCS-10798
```
[x] Yes
[ ] No
```
=>  SSCS-10798 Send new hearing message on postponement

build.gradle
=> SSCS-10177 Fix version declaration

.gitignore, build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UpdateOtherPartyDataIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UpdateSscs5OtherPartyDataIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/OtherPartyDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/deathofappellant/DeathOfAppellantAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/fenoaction/FeNoActionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/fenoaction/FeNoActionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/withdrawnappeals/AdminAppealWithdrawnHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/withdrawnappeals/DwpActionWithdrawalHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipPointsConditionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/OtherPartyDataUtilTest.java, src/test/resources/callback/updateOtherPartyCallback.json, src/test/resources/callback/updateOtherPartySscs5Callback.json
https://tools.hmcts.net/jira/browse/SSCS-10882
```
[x] Yes
[ ] No
```
=> SSCS-10882 Fixing Conflicting IDs

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/UpdateListingRequirementsUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/UpdateListingRequirementsUtilTest.java
https://tools.hmcts.net/jira/browse/SSCS-10892
```
[ ] Yes
[x] No
```
=> SSCS-10892 Remove Reserve to Judge

src/cftlib/java/uk/gov/hmcts/reform/sscs/AdditionalComposeServiceRunner.java
=> Fix cftlib import.

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceBase.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTestBase.java
https://tools.hmcts.net/jira/browse/SSCS-10357
CCD - Add appellants name to body of final decision & adjournment notice.
```
[ ] Yes
[x] No
```
=> SSCS-10357 add appellants name when generating notice

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
Reverts hmcts/sscs-tribunals-case-api#2913
=> Revert "SSCS-10824" SSCS-10940

dependency-check-suppressions.xml
=> Moved suppressions to november

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionposteponementrequest/ActionPostponementRequestTest.java
https://tools.hmcts.net/jira/browse/SSCS-10959
```
[ ] Yes
[x] No
```
=> SSCS-10959 ActionPostponementRequestTest Fix

dependency-check-suppressions.xml
=> Suppress jackson databind

src/main/java/uk/gov/hmcts/reform/sscs/util/OtherPartyDataUtil.java
https://tools.hmcts.net/jira/browse/SSCS-10939
```
[ ] Yes
[x] No
```
=> SSCS-10939 - Unable to submit Update to Reasonable Adjustments Event

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10968
```
[ ] Yes
[ ] No
```
=> SSCS-10968 cve suppression

build.gradle, src/cftlib/java/uk/gov/hmcts/reform/sscs/AdditionalComposeServiceRunner.java, src/cftlib/resources/docker/cft-lib-ref-data-wiremock.yml, src/cftlib/resources/scripts/start.sh, src/cftlib/resources/wiremock/reference-data/mappings/court-venues-mapping.json, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionposteponementrequest/ActionPostponementRequestTest.java
https://tools.hmcts.net/jira/browse/SSCS-10925
=> SSCS-10925 Add wiremock stub, fetch secrets automatically.

audit.json
=> Suppress false positives

build.gradle, dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/AssociatedCaseLinkHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceBase.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
https://tools.hmcts.net/jira/browse/SSCS-10985
```
[ ] Yes
[x] No
```
=> SSCS-10985 CVE Fix Commons Bump

audit.json
https://tools.hmcts.net/jira/browse/SSCS-10912
OWASP Zap timestamp suppression
```
[ ] Yes
[x] No
```
=> SSCS-10912 - OWASP Zap timestamp suppression

.github/renovate.json
=> Renovate PR Groups

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9772
```
[ ] Yes
[x] No
```
=> SSCS-9772 - use uploaded document when writing adjournment notice

dependency-check-suppressions.xml
Extends expired suppressions until Nov 8th to allow for spring upgrade to be merged
Temporary for https://tools.hmcts.net/jira/browse/SSCS-10358
```
[ ] Yes
[ x ] No
```
=> extends expired suppressions until Nov 8th

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml
=> SSCS-10924 Change to tf managed secret.

audit.json
=> SSCS-11169 - new ignore entry for audit.json

dependency-check-suppressions.xml
=> adds suppression for CVE-2021-37533

charts/sscs-tribunals-api/Chart.yaml
Update java chart version to 4.0.4
=> Update java chart version to 4.0.4

build.gradle, config/owasp/suppressions.xml
=> SSCS-11249-a - suppress CVE-2022-3064

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandlerTest.java
=> SSCS-11254 - add idam surname to payload to view it on the doc

Jenkinsfile_CNP, config/owasp/suppressions.xml
=> SSCS-11249 - jenkins minor change

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java
=> SSCS-11396 - Unable to submit write adjournment notice event

build.gradle
=> SSCS-10316 - upgrade sscs-common to v4.25.2

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToStartHandler.java
=> SSCS-11393 : Removed log line causing NPE

config/owasp/suppressions.xml
=> suppresses CVE-2022-45688

charts/sscs-tribunals-api/values.yaml
=> SSCS-11485 : Added alias for App Insights secret

config/owasp/suppressions.xml
=> suppress CVE-2023-24998

build.gradle, charts/sscs-tribunals-api/Chart.yaml, config/owasp/suppressions.xml
=> upgrade and suppress

src/cftlib/java/uk/gov/hmcts/reform/sscs/CftlibConfig.java
Quick fix to local setup after 9939 merge
=> Quick fix to local setup after 9939 merge

charts/sscs-tribunals-api/Chart.yaml
SSCS-11535
```
[ ] Yes
[ ] No
```
=> bump chart version

charts/sscs-tribunals-api/Chart.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java
=> Sscs 11535 fix

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-11534
Fix for 10893, needs feature flag otherwise missing field in PROD.
```
[ ] Yes
[x] No
```
=> SSCS-11534 - Add adjournment feature flag for missing field error

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java
uncontrolled
```
[ ] Yes
[ ] No
```
=> remove excess logging and revert to use getJudicialUserFullName

config/owasp/suppressions.xml
=> Updating CVE suppressions

config/owasp/suppressions.xml
uncontrolled
```
[ ] Yes
[ ] No
```
=> fix suppression dates

Dockerfile
Fixing pipeline
```
[ ] Yes
[x] No
```
=> sscs-11550 Fixing pipeline

config/owasp/suppressions.xml
=> updates suppressions

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java
=> add log to AFE submit handler

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java
=> further evidence original sender regex fix

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandlerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/FurtherEvidenceActionDynamicListItems.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-11667
```
[ ] Yes
[x] No
```
=> add flag around populating action further evidence list SSCS-11667

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/OtherPartyDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventHandlerTest.java
…cs2 cases
```
[ ] Yes
[ ] No
```
=> SSCS-11601 - force to add other parties during upload response for sscs2 cases

Dockerfile
=> revert app insights

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
Preview db init fix
```
[ ] Yes
[x] No
```
=> Preview db init fix

config/owasp/suppressions.xml
CVE Suppression - 05.06.2023
```
[ ] Yes
[x] No
```
=> CVE Suppression - 05.06.2023

build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestinfo/RequestForInformationAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestinfo/RequestForInformationAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestinfo/RequestForInformationAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestinfo/RequestForInformationAboutToSubmitHandlerTest.java, src/test/resources/callback/requestInfoCallback.json
…ormation
```
[ ] Yes
[ ] No
```
=> SSCS-10973 - rename requestInfoIncompleteApplication to Requestforinformation

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
=> reset preview env values to original

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
tya disabled in preview by default
added instruction how to enable it for preview
```
[ ] Yes
[x] No
```
=> Preview environment fixes

charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/cftlib/resources/docker/cft-lib-doc-stack.yml
Azurite new repository for local development env
```
[ ] Yes
[x] No
```
=> Azurite new repository

config/owasp/suppressions.xml
CVE Fix - 27.06.23
```
[ ] Yes
[x] No
```
=> CVE Fix - 27.06.23

build.gradle, config/owasp/suppressions.xml
CVE Fix - 03.07.23
```
[ ] Yes
[x] No
```
=> CVE Fix - 03.07.23

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/posthearingreview/PostHearingReviewMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/posthearingreview/PostHearingReviewSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsUtilTest.java
=> Sscs 10606 grant refused lta

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
Fixed subscription name for tya
```
[ ] Yes
[ ] No
```
=> fixed subscription name for tya

Jenkinsfile_nightly
Fix Broken Pipeline
```
[ ] Yes
[x] No
```
=> Fix Broken Pipeline

src/main/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginService.java, src/test/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CitizenLoginServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-11856
Back out change due to prod issues
```
[ ] Yes
[x] No
```
=> SSCS-11856 Back out attempted other party fix

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
tya topic name fix
```
[ ] Yes
[x] No
```
=> tya topic name fix

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
evidence-share topic subscription fix for preview environment
```
[ ] Yes
[x] No
```
=> evidence-share topic subscription fix

build.gradle, config/owasp/suppressions.xml
CVE Fix 31.07.2023
```
[ ] Yes
[x] No
```
=> CVE Fix 31.07.2023

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml
Increased default memory limit
```
[ ] Yes
[x] No
```
=> memory limit increase

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
Asb preview fix
```
[ ] Yes
[x] No
```
=> Asb preview fix

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-11486
Clear the interloc referral reason when
issuing a new direction or decision
```
[ ] Yes
[X] No
```
=> SSCS-11486 Clear interloc referral reason

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
=> changed limits on pods

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.yaml
https://tools.hmcts.net/jira/browse/SSCS-11993
Unable to allocate a Case role to staff user
```
[ ] Yes
[x] No
```
=> SSCS-11993 Fix case assignment on preview

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DynamicListLanguageUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
=> SSCS-11585 - Dropdown List for Language selection values in update to case data 

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
uncontrolled
```
[ ] Yes
[ ] No
```
=> remove benefit code check

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ccd/UcDecisionNoticeFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/evidence/EvidenceDocumentUploadTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java
=> Comment out tests

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ccd/EsaDecisionNoticeFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ccd/UcDecisionNoticeFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/evidence/EvidenceDocumentUploadTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionfurtherevidence/ActionFurtherEvidenceAboutToStartHandlerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/createbundle/CreateBundleAboutToSubmitHandlerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java
Enable tests
```
[ ] Yes
[ X] No
```
=> Enable tests

build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueNoticeHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminactioncorrection/AdminActionCorrectionAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminactioncorrection/AdminActionCorrectionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminactioncorrection/AdminActionCorrectionSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackController.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminactioncorrection/AdminActionCorrectionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminactioncorrection/AdminActionCorrectionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adminactioncorrection/AdminActionCorrectionSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackControllerTest.java
=> Sscs 10581 admin can process correction or send a correction request to judge for review

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-11993
Deploy am-org-role-mapping-service to preview
```
[ ] Yes
[x] No
```
=> SSCS-11993 Deploy am-org-role-mapping-service to preview

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java
=> Tribs: add yes check for interpreterRequired

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java
=> Tribs: add null check

build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/handlers/uploaddocument/uploadDocumentFECallback.json, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/resources/callback/caseUpdated.json
Reverts hmcts/sscs-tribunals-case-api#3393
=> Revert "SSCS-11363-Add-Address-Validation"

build.gradle, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/sscs/config/HttpClientConfiguration.java
=> revert preview db changes

config/owasp/suppressions.xml, src/main/resources/config/application.properties
=> Suppress vulnerabilities

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToStartHandlerTest.java
SSCS-12019
```
[ ] Yes
[ ] No
```
=> update write final decision handler

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsUtilTest.java
SSCS-11764
```
[ ] Yes
[ ] No
```
=> Tribs: refactor to update hearing channel in update listing requirements

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerMainTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTestBase.java, src/test/resources/callback/adjournCaseGeneratedFaceToFaceWhenCaseNotListedStraightAwayWithoutDirectionsMade.json, src/test/resources/callback/adjournCaseGeneratedFaceToFaceWithInterpreterNotRequiredAndLanguageSet.json, src/test/resources/callback/adjournCaseGeneratedFaceToFaceWithInterpreterRequiredAndLanguageSet.json
=> Sscs 11998 demo testing

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java
=> add null check

Jenkinsfile_CNP, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-12142
Testing on a separate PR
=> SSCS-12142 Error allocating tribunal members

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createcase/CreateCaseAboutToSubmitHandler.java
Handle benefit type before creating appeal pdf
=> Handle benefit type before creating appeal pdf

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-524
Skip validation for rep if org is present
Null check for rep name
=> SSCSCI-524

charts/sscs-tribunals-api/values.ccd.preview.template.yaml, config/owasp/suppressions.xml
this is required to enable secrets to be written into config props on the SYA frontend dependency
=> add ALLOW_CONFIG_MUTATIONS flag to fix preview deployments

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueNoticeHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/uc/UcIssueFinalDecisionAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-12157
Fixed an issue with blank decision notice
=> Fixed an issue with blank decision notice

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-12096
Switch from using PostgreSQL pod to Azure flex db server on preview
=> SSCS-12096 Switch to flex db server on preview

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-595
After entering the language needed for interpreter language, the value is set and appears in Appeal Details tab.
=> SSCSCI-595 - Interpreter Language not showing in Appeal Details

build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.yaml, config/owasp/suppressions.xml, src/IntegrationTests/resources/config/application_it.properties, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenLoginTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java, src/functionalTest/resources/config/application_functional.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueNoticeHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdClient.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/uc/UcIssueFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdClientTest.java
https://tools.hmcts.net/jira/browse/SSCS-12212
Pre Hearing Worktypes added to events 'validsendtointerloc' and 'tcwReferToJudge'
=> SSCS-12212 Pre Hearing work type

src/main/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdClient.java
- fix ES query used to search for citizen user cases
=> fix ES match_all query

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-12223
Testing task initiation for reviewPostponementRequestJudge
=> SSCS-12223 Testing

README.md, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenLoginTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/mya/IdamTestApiRequests.java
=> CitizenLoginTest fix

build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/IntegrationTests/resources/config/application_it.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueNoticeHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceBase.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writestatementofreasons/WriteStatementOfReasonsMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writestatementofreasons/WriteStatementOfReasonsPreviewService.java, src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/NoticeIssuedTemplateBody.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTestBase.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writestatementofreasons/WriteStatementOfReasonsMidEventHandlerTest.java
=> Sscs 12091 update sor notice

charts/sscs-tribunals-api/values.ccd.preview.template.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-12274
=> SSCS-12274 testing

config/owasp/suppressions.xml
=> Updating suppressions

Jenkinsfile_CNP, build.gradle, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/WorkAllocationHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/WorkAllocationHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-11790
Setting up mergeRoleList Function.
=> SSCS-11790 Create additional prepare for hearing tasks

build.gradle
=> Update sscs-common to 5.2.8

charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-621
Allow user to select "review by Judge" for Action Further Evidence event with postponement document as the document type SO THAT Judges are allowed to review
=> SSCSCI-621 - Allow user to select "review by Judge" for postponement event

src/test/resources/json/sya.json, src/test/resources/json/sya_with_benefit_type.json
=> integration tests fix

build.gradle
SSCSCI-669 - Update sscs-common to 5.3.1
=> SSCSCI-669 - Update sscs-common to 5.3.1

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandler.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-718
Add check for hearing date when evaluating if hearing is in the past. 
New feature flag UPLOAD_HEARING_FILTER_ENABLED
=> SSCSCI-718: Handle NPE in UploadHearingRecordingAboutToStartHandler

config/owasp/suppressions.xml
Added new CVE to suppressions: CVE-2024-25710
=> Updated suppression

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-762
Update sscs-common to 5.3.2
=> SSCSCI-762: Update common version

config/owasp/suppressions.xml, src/contractTest/java/uk/gov/hmcts/reform/sscs/ccd/ReadForCaseWorkerConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/sscs/ccd/caseassignment/CaseAssignmentUserRolesConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/sscs/ccd/idam/IdamApiConsumerTest.java, src/contractTest/resources/config/application_contract.properties, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/WorkAllocationHandler.java
https://tools.hmcts.net/jira/browse/SSCS-12385
Pact tests update
=> Pact tests update

build.gradle
=> Disable dependency check on commit

src/test/resources/sya/allDetailsNonSaveAndReturnCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdChildSupport.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdSscs5.json, src/test/resources/sya/allDetailsNonSaveAndReturnNoMrnDateCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnWithInterlocCcd.json
=> Fix functional tests

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
Preview ccd-defs and wa flag update
=> Preview ccd-defs and wa flag update

Jenkinsfile_CNP, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/createbundle/CreateBundleAboutToSubmitHandlerFunctionalTest.java
[SSCSSI-94](https://tools.hmcts.net/jira/browse/SSCSSI-94)
Disable bundle Fts on preview
=> SSCSSI-94: Disable bundle Fts on preview

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/createbundle/CreateBundleAboutToSubmitHandlerFunctionalTest.java
[SSCSSI-94](https://tools.hmcts.net/jira/browse/SSCSSI-94)
Fix Create Bundle tests running in master
=> SSCSSI-94: Fix Bundle FTs in master

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceSubmittedCallbackHandlerTest.java
Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SSCSSI-57
This PR only changes Action further evidence submitted callback when further action is issue to all parties
=> Use update case v2 to update case when further action is issue to all parties

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestSubmittedCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestSubmittedCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/decisionissued/DecisionIssuedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-12319
Added missing feature flag
=> Sscs 12319 missing feature flag

Jenkinsfile_CNP, README.md, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.preview.template.yaml, charts/sscs-tribunals-api/values.yaml
This reverts commit bcfb3fd4aa4fd6cdb26055d758d0210f4d48a0b3.
=> Revert "SSCSCI-529 (#3575) Enable Hearings on preview "

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-12338
https://tools.hmcts.net/jira/browse/SSCS-12371
Deploy CCD defs S12371BnonProd for testing
=> Testing SSCS-12371 / SSCS-12338 Updated RoleToAccessProfile mappings

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandlerTest.java
=> Revert SSCS-11648 Commit

build.gradle
Update sscs-common to latest version
=> SSCSCI - Update commons version

Jenkinsfile_CNP, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml
https://tools.hmcts.net/jira/browse/SSCSSI-159
Also autosyncs to demo/ perftest on master commit to avoid manual merges.
=> SSCSSI-159 | Use new sendgrid secret managed in this repo

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
Orchestrator only listens to topic
https://tools.hmcts.net/jira/browse/SSCSSI-156 
Its unused in tests as per the search as well.
=> Remove unused Queue

src/main/java/uk/gov/hmcts/reform/sscs/config/MessagingConfig.java, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCSSI-236
- Reuses the activemq container for publishing messages to topic
=> SSCSSI-236 Fix local setup with bootccd

README.md, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/mya/EvidenceUploadTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java
=> Fix FT tests

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-849
Updated suppression date and removed CVE-2024-1597 as it is not needed.
=> Suppression date fix

Jenkinsfile_CNP, README.md, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.wa.preview.template.yaml
Test and fix preview deployment
=> Fix preview deployment

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/SSCSSI-245
Add missing environment variables
=> SSCSSI-245 | Fix Nightly evidence share tests

charts/sscs-tribunals-api/values.ccd.preview.template.yaml
=> update ccd preview image

build.gradle, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.preview.template.yaml, charts/sscs-tribunals-api/values.wa.preview.template.yaml, charts/sscs-tribunals-api/values.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/sendtofirsttier/SendToFirstTierSubmittedHandler.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/sendtofirsttier/SendToFirstTierSubmittedHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSSI-332
- Relies on https://github.com/hmcts/sscs-common/pull/1601
- Tested on preview
=> Use handleCcdCallbackMapV2update for sent to first tier submitted event handler

build.gradle, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml
- https://tools.hmcts.net/jira/browse/SSCSCI-893
- set common snapshot version to test venue updates
=> set common snapshot version to test venue updates

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java, src/test/resources/sya/allDetailsNonSaveAndReturnCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdChildSupport.json, src/test/resources/sya/allDetailsNonSaveAndReturnCcdSscs5.json, src/test/resources/sya/allDetailsNonSaveAndReturnNoMrnDateCcd.json, src/test/resources/sya/allDetailsNonSaveAndReturnWithInterlocCcd.json
https://tools.hmcts.net/jira/browse/SSCSCI-878
Test ccd pr in preview and allow 'hearingRoute' to appear in the 'Listing requirements' tab from when a case is in valid appeal state
=> SSCSCI-878: Listing requirement tab missing (Latest)

config/owasp/suppressions.xml, src/cftlib/resources/docker/cft-lib-doc-stack.yml
https://tools.hmcts.net/jira/browse/SSCSCI-924
- Updated hardcoded password to resolve fortify issue
- Updated suppression date
=> SSCSCI-924 Fortify issue fix

build.gradle
=> update sscs-common to 5.9.0

build.gradle, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml
- https://tools.hmcts.net/jira/browse/SSCSCI-923
- update Reading venue address
=> SSCS CI-923: update Reading venue address

src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedSubmittedHandler.java
https://tools.hmcts.net/jira/browse/SSCSCI-954
=> Added logging for feign exception to capture validation/warning from ccd callback

src/main/java/uk/gov/hmcts/reform/sscs/config/MessagingConfig.java, src/main/resources/config/application.properties
Reverts hmcts/sscs-tribunals-case-api#3890
=> Revert "SSCSSI-352 | Fix prefetching issue with service bus topic message listeners"

build.gradle, charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-954
=> Use ignore warning field from case data to determine if the warning has to be ignored

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.ccd.preview.template.yaml
https://tools.hmcts.net/jira/browse/SSCSSI-386
Updating charts to fix preview ccd enabled build
- [ x] commit messages are meaningful and follow good commit message guidelines
=> SSCSSI-386: Updating charts to fix preview ccd enabled build

charts/sscs-tribunals-api/values.ccd.preview.template.yaml, charts/sscs-tribunals-api/values.wa.preview.template.yaml, src/cftlib/java/uk/gov/hmcts/reform/sscs/CftlibConfig.java
https://tools.hmcts.net/jira/browse/SSCSCI-1045
Add ibca user to cft lib set up and preview yaml files
=> SSCSCI-1045

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml, src/main/java/uk/gov/hmcts/reform/sscs/service/servicebus/TopicConsumer.java, src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCSSI-400
Changing property to make it configurable.
=> Make callback retries configurable through a separate env var

charts/sscs-tribunals-api/values.preview.template.yaml
=> Fix PR builds without ccd label

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/evidenceshare/DecisionIssuedFunctionalTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-1025
update functional test to remove assertion dependent on posthearings being enabled
=> SSCSCI-1025 - update functional test for posthearings

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/util/DynamicListLanguageUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/util/DynamicListLanguageUtilTest.java
Reverts hmcts/sscs-tribunals-case-api#3953
=> Revert "SSCSCI-1028: move mrd reference lookup logic to common"

Jenkinsfile_CNP
=> try all secrets, all the time

charts/sscs-tribunals-api/values.preview.template.yaml
=> Add IBA domain to sya

infrastructure/database.tf
to enable trying db migration managed through Jenkins.
=> Add new secrets to comply with library naming

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml
Secrets have been created and confirmed through portal.
=> Move secrets to use tribs

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/AbstractedCaseUpdatedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToStartHandlerTest.java
=> unit test updates after commons release

charts/sscs-tribunals-api/Chart.yaml
=> Upgrade chart version for fixing Jenkins publish

src/main/java/uk/gov/hmcts/reform/sscs/config/HighLevelDataSetupApp.java
=> tolerate HLD failure in demo

build.gradle
commons upgrade needed for caseloader
=> SSCSCI: commons upgrade for caseloader

src/main/java/uk/gov/hmcts/reform/sscs/config/MessagingConfig.java, src/main/resources/config/application.yaml
Currently we are not retying connections if they have a fatal failures
=> Add retry on exception with connection

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/handlers/AdminAppealWithdrawnNotificationsTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/EvidenceReceivedFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/JointPartyFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/NotificationsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/OtherPartyFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/WelshNotificationsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/WithRepresentativePersonalisationTest.java
To enable rollback for https://tools.hmcts.net/jira/browse/SSCSCI-1137
=> Disable functional tests as notifications to unblock rollback deployment

README.md
=> Fix README.md to re-trigger clean build

README.md
=> Fix key name

src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java
=> fix for IBC create case

Jenkinsfile_CNP
Reverts hmcts/sscs-tribunals-case-api#4175
=> Revert "Disable demo sync temporarily to avoid overriding demo definition"

definitions/benefit/sheets/CaseEvent/CaseEvent-nonprod.json
https://tools.hmcts.net/jira/browse/SSCSCI-1340
Change case outcome migration event name to approved name
=> SSCSCI-1340 - Set Case Outcome Migration event name

build.gradle
Reverts hmcts/sscs-tribunals-case-api#4246
=> Revert "Update Testing"

definitions/benefit/sheets/CaseEventToFields/CaseEventToFields-nonprod.json, definitions/benefit/sheets/CaseEventToFields/CaseEventToFields.json
See [SSCSCI-1534](https://tools.hmcts.net/jira/browse/SSCSCI-1534)
=> SSCSCI-1534 making isMedicalMemberRequired an optional field

definitions/benefit/sheets/CaseEventToComplexTypes/CaseEventToComplexTypes-caseUpdated.json
See [SSCSCI-1505](https://tools.hmcts.net/jira/browse/SSCSCI-1505)
removing appellant.addressLine3 from update to case data
=> SSCSCI-1505

build.gradle
See [SSCSCI-1547](https://tools.hmcts.net/jira/browse/SSCSCI-1547)
=> SSCSCI-1547 commons bump

bin/create-xlsx.sh
=> Fix xlsx generation locally and for mirrord

build.gradle
Reverts hmcts/sscs-tribunals-case-api#4244
=> Revert "Update Automated Checks"

definitions/test/pages/tabs/hearings.ts
Fix was applied & tested on below build and confirmed working
https://build.hmcts.net/view/SSCS/job/HMCTS_j_to_z_Nightly/job/sscs-tribunals-case-api/job/nightly-dev/101/
=> fix nightly

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.yaml
=> Disable stitching by default

build.gradle
=> switch to org commonmark

README.md, build.gradle
These tests do not work and are not part of the pipeline, so may have been broken for some time.
=> Remove PI tests

definitions/benefit/sheets/CaseEvent/CaseEvent-nonprod.json
https://tools.hmcts.net/jira/browse/SSCSCI-1732
ShowEventNotes for amendhearing
=> SSCSCI-1732: ShowEventNotes for amendhearing

src/main/resources/config/application.yaml
https://tools.hmcts.net/jira/browse/SSCSCI-1615
=> SSCSCI-1615

src/main/resources/config/application.yaml
https://tools.hmcts.net/jira/browse/SSCSCI-1619
added templates
https://tools.hmcts.net/jira/browse/SSCSCI-1619
=> SSCSCI-1619

src/main/resources/config/application.yaml
https://tools.hmcts.net/jira/browse/SSCSCI-1618
added templates to yaml file
=> SSCSCI-1618

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/NotificationsFunctionalTest.java
=> SSCSCI-1388: Investigate and fix: Nightly build failures

.gitignore, definitions/test/api/client/sscs/factory/appeal.type.factory.ts, definitions/test/api/data/payload/create-appeal/ibca_sya.json, definitions/test/e2e/iba/iba-appeal-oral.spec.ts, definitions/test/e2e/iba/iba-appeal-paper-scottish.spec.ts, definitions/test/fixtures/steps/base.ts, definitions/test/fixtures/steps/generate.appeal.pdf.ts, definitions/test/fixtures/steps/update.other.party.data.ts, definitions/test/fixtures/steps/update.to.case.data.ts, definitions/test/lib/steps.factory.ts, definitions/test/pages/common/homePage.ts, definitions/test/pages/content/iba/iba.casedata_en.json, definitions/test/pages/content/update.other.party.data_en.json, definitions/test/pages/create.update.to.case.data.page.ts, definitions/test/pages/tabs/appealDetails.ts, definitions/test/pages/tabs/summary.ts, definitions/test/pages/update.other.party.data.page.ts
[SSCSCI-1520](https://tools.hmcts.net/jira/browse/SSCSCI-1520)
Create IBA Oral and IBA Paper cases through XUI.
Perform Update to case data event on both the cases and validate.
Perform Generate PDF event on both the cases and valudate.
Perform Update other party event on both the cases and validate.
```
$ npx playwright test --config ./playwright.config.ts --workers=2 --project chromium --reporter=html --grep @ibc
Running 8 tests using 2 workers
[chromium] › iba\iba-appeal-paper-scottish.spec.ts:24:7 › Create IBA Paper Scottish case appeal and perform few events › Update to case data for IBA Paper case
url of the page is ######## https://manage-case.aat.platform.hmcts.net/cases/case-search
case type dropdown value is ###### SSCS Case 6.4.19 AAT
[chromium] › …
```
=> Sscsci 1520:  IBC oral and paper case journeys via XUI and associated events.

definitions/test/fixtures/steps/hearing.ts, definitions/test/pages/listing.requirements.page.ts
=> test fixes

definitions/test/common/web.action.ts, definitions/test/e2e/appeal-dormant.spec.ts, definitions/test/e2e/hearing-request.spec.ts, definitions/test/e2e/manage-documents.spec.ts, definitions/test/fixtures/steps/appeal.dormant.ts, definitions/test/fixtures/steps/base.ts, definitions/test/fixtures/steps/confirm.case.lapsed.ts, definitions/test/fixtures/steps/evidence.reminder.ts, definitions/test/fixtures/steps/request.time.extension.ts, definitions/test/fixtures/steps/update.not.listable.ts, definitions/test/fixtures/steps/upload.hearing.ts, definitions/test/fixtures/steps/upload.response.ts, definitions/test/fixtures/steps/urgent.hearing.ts, definitions/test/pages/common/event.name.event.description.ts, definitions/test/pages/common/homePage.ts, definitions/test/pages/not.listable.page.ts, definitions/test/pages/tabs/hearings.ts
=> Flakiness fix

charts/sscs-tribunals-api/values.preview.template.yaml
=> removing value from preview yaml

src/main/java/uk/gov/hmcts/reform/sscs/evidenceshare/service/placeholders/SorPlaceholderService.java, src/main/java/uk/gov/hmcts/reform/sscs/tyanotifications/config/NotificationConfig.java, src/main/java/uk/gov/hmcts/reform/sscs/tyanotifications/config/properties/EvidenceProperties.java, src/main/java/uk/gov/hmcts/reform/sscs/tyanotifications/personalisation/Personalisation.java, src/main/resources/config/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/evidenceshare/service/CcdNotificationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/evidenceshare/service/placeholders/SorPlaceholderServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/tyanotifications/personalisation/PersonalisationTest.java
See [SSCSCI-1506](https://tools.hmcts.net/jira/browse/SSCSCI-1506)
=> SSCSCI-1506

Jenkinsfile_CNP
See [SSCSCI-1845](https://tools.hmcts.net/jira/browse/SSCSCI-1845)
resync demo with master
=> SSCSCI-1845 - demo sync

definitions/test/fixtures/steps/hearing.ts
=> Update venue count in tribs-api nightly tests

Jenkinsfile_CNP
See [SSCSCI-1571](https://tools.hmcts.net/jira/browse/SSCSCI-1571)
Temporarily remove demo ccd sync for testing changes for SSCSCI-1571, SSCSCI-1802, and SSCSCI-1728 in demo
=> SSCSCI-1571 - remove demo sync

definitions/benefit/sheets/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/benefit/sheets/AuthorisationCaseField/AuthorisationCaseField-panelComposition.json, definitions/benefit/sheets/CaseField/CaseField-nonprod.json, definitions/benefit/sheets/CaseField/CaseField-panelComposition.json, definitions/benefit/sheets/ComplexTypes/ComplexTypes-nonprod.json, definitions/benefit/sheets/ComplexTypes/ComplexTypes-panelComposition.json, definitions/benefit/sheets/FixedLists/FixedLists-nonprod.json, definitions/benefit/sheets/FixedLists/FixedLists-panelComposition.json
=> SSCSCI-1728: add ccd field to match caseData object

definitions/test/pages/action.further.evidence.page.ts
https://static-build.hmcts.net/static-files/QJfsi8glmI7uxWvx03N6fk0xRvFtKa5Z4PCTRJ2izZwxNzUxMDMxMzA2NzU1OjM2OjJmN2VmODBlLThlZTAtNDEwZi1iNWMzLWFhNTNkOTFkNmZiNTp2aWV3L1NTQ1Mvam9iL0hNQ1RTX2pfdG9fel9OaWdodGx5L2pvYi9zc2NzLXRyaWJ1bmFscy1jYXNlLWFwaS9qb2IvbmlnaHRseS1kZXYvMjgxL2FydGlmYWN0/definitions/test/playwright-report/index.html
=> Tiny hot fix for error message

src/main/java/uk/gov/hmcts/reform/sscs/controller/EvidenceUploadController.java
Suppress [java:S6863](https://sonarcloud.io/organizations/hmcts/rules?open=java%3AS6863&rule_key=java%3AS6863) for EvidenceUploadController
=> suppress sonarqube false positive

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confirmpanelcomposition/ConfirmPanelCompositionAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/confirmpanelcomposition/ConfirmPanelCompositionAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToSubmitHandlerTest.java
See [SSCSCI-1837](https://tools.hmcts.net/jira/browse/SSCSCI-1837)
Sync FQPM and medical members between "Confirm panel composition" event and "Update Listing Req" Event
Checked if ACs pass in preview
=> SSCSCI-1837: sync FQPM between events

src/main/java/uk/gov/hmcts/reform/sscs/bulkscan/validators/FormTypeValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscan/validators/FormTypeValidatorTest.java, src/test/resources/schema/malformed_schema.json
See [SSCSCI-1972](https://tools.hmcts.net/jira/browse/SSCSCI-1972)
Fixing Fortify issue
> The function tryLoadSscsSchema() in FormTypeValidator.java sometimes fails to release a system resource allocated by getResourceAsStream() on line 88.The program can potentially fail to release a system resource.
Passed Fortify Scan in the nightly-dev branch
=> SSCSCI Fortify fix for nightly pipelines

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPanelMapping.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPanelMappingTest.java
See [SSCSCI-1877](https://tools.hmcts.net/jira/browse/SSCSCI-1877)
Add a null check for session category
=> SSCSCI-1877 - Universal Credit Panel Composition

build.gradle
See [SSCSCI-1978](https://tools.hmcts.net/jira/browse/SSCSCI-1978)
- upgrade sscs-common to v6.3.8 (panelComp config update)
- will be tested as part of ILA regression 
=> upgrade sscs-common to v6.3.8 (panelComp config update)

definitions/test/common/web.action.ts, definitions/test/e2e/update-listing-requirements.spec.ts, definitions/test/e2e/upload-response.spec.ts, definitions/test/fixtures/steps/hearing.ts, definitions/test/fixtures/steps/update.listing.requirements.ts, definitions/test/fixtures/steps/upload.response.ts, definitions/test/lib/steps.factory.ts, definitions/test/pages/content/listing.requirements.json, definitions/test/pages/listing.requirements.page.ts
https://tools.hmcts.net/jira/browse/SSCSCI-1808
Test evidence
=> Add tests for ILA feature

definitions/test/fixtures/steps/upload.response.ts
Tests passing on Preview  : -
Tests passing on AAT : -
=> fix preview failing tests

definitions/test/e2e/hearing-request.spec.ts
=> Skip flaky tests need proper fix

build.gradle
- See [SSCSCI-1729](https://tools.hmcts.net/jira/browse/SSCSCI-1729)
- bump up common version to 6.3.10
- upgrade includes adding equals method to PanelMemberComposition
=> SSCSCI-1729: bump up common version to 6.3.10

build.gradle
- See [SSCSCI-2071](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
- upgrade common to test added panelCategory config
=> SSCSCI-2071: upgrade common to test new panelCategory config

charts/sscs-tribunals-api/Chart.yaml, charts/sscs-tribunals-api/values.preview.template.yaml, charts/sscs-tribunals-api/values.yaml
update redis repo used as Bitnami are no longer providing free images
=> SSCSCI - Update Redis
