- src/main/resources/templates/appellant_appeal_template.html
- Add Reasons for appeal to the pdf template.
- To coincide with the Add another functionality in the frontend.
- Loop over the reasons to appeal and display the `what your appealing` question/answer and `why your appealing` question/answer.
> Reasons for appeal PDF changes

- src/main/resources/templates/appellant_appeal_template.html
- Add new fields `interpreterLanguageType`, `signLanguageType`
- Add other `option`
- Change `disabledAccess` to `accessibleHearingRoom`
**Example:**
- If `sign language interpreter` has been selected and the `signLanguageType` field has a value then display that value else display `Required`. Display `Not required` when sign language interpreter hasn't been selected.
> Update PDF for hearing arrangements section

- docker-compose.yml
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/variables.tf
- src/IntegrationTests/java/uk/gov/hmcts/sscs/ccd/properties/CoreCaseDataPropertiesTest.java
- src/IntegrationTests/java/uk/gov/hmcts/sscs/sya/SyaEndpointsIt.java
- src/main/java/uk/gov/hmcts/sscs/ccd/properties/CoreCaseDataProperties.java
- src/main/java/uk/gov/hmcts/sscs/service/ccd/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/sscs/service/ccd/CreateCoreCaseDataService.java
- src/main/java/uk/gov/hmcts/sscs/service/ccd/ReadCoreCaseDataService.java
- src/main/java/uk/gov/hmcts/sscs/service/ccd/UpdateCoreCaseDataService.java
- src/main/java/uk/gov/hmcts/sscs/service/idam/AuthTokenSubjectExtractor.java
- src/main/java/uk/gov/hmcts/sscs/service/idam/IdamService.java
- src/main/resources/config/application.properties
- src/test/java/uk/gov/hmcts/sscs/service/ccd/CreateCoreCaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/sscs/service/ccd/ReadCoreCaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/sscs/service/ccd/UpdateCoreCaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/sscs/service/idam/AuthTokenSubjectExtractorTest.java
- src/test/java/uk/gov/hmcts/sscs/service/idam/IdamServiceTest.java
- src/test/java/uk/gov/hmcts/sscs/util/SerializeJsonMessageManager.java
https://tools.hmcts.net/jira/browse/SSCS-2877
IDAM user_id is taken from the Authorisation token, instead of being loaded from application configuration.
```
[ ] Yes
[x] No
```
> SSCS-2877 User id extracted from IDAM authorization token

- src/main/java/uk/gov/hmcts/sscs/controller/PostCodeController.java
- src/main/java/uk/gov/hmcts/sscs/exception/AirLookupServiceException.java
- src/main/java/uk/gov/hmcts/sscs/service/AirLookupService.java
- Errors need to be logged in a certain way in order for app insights to correctly report. Fixed the AirLookup exceptions to comply with what is required
> SSCS-3687 Log tribunal errors correctly

- src/main/java/uk/gov/hmcts/sscs/builder/TrackYourAppealJsonBuilder.java
- src/test/java/uk/gov/hmcts/sscs/builder/TrackYourAppealJsonBuilderTest.java
- src/test/java/uk/gov/hmcts/sscs/util/SerializeJsonMessageManager.java
- src/test/resources/tya/emptyEventCcd.json
- When an empty event (date) comes back from CCD for TYA then remove these events so no NPE is thrown on sort
> [PREVIEW] SSCS-3816 Handle empty events

- src/IntegrationTests/java/uk/gov/hmcts/sscs/service/ReadCcdServiceRetryAndRecoverTest.java
- src/IntegrationTests/java/uk/gov/hmcts/sscs/sya/SyaEndpointsIt.java
- src/main/java/uk/gov/hmcts/sscs/service/CcdService.java
- src/main/java/uk/gov/hmcts/sscs/service/SubmitAppealService.java
- src/main/java/uk/gov/hmcts/sscs/service/ccd/ReadCoreCaseDataService.java
- src/test/java/uk/gov/hmcts/sscs/service/CcdServiceTest.java
- src/test/java/uk/gov/hmcts/sscs/service/SubmitAppealServiceTest.java
- If a case with same nino, benefit type and mrn date already exists in CCD then prevent it from being added again
- Continue to Robotics and PDF as duplicates are handled on their side anyway
> [PREVIEW] SSCS-3805 Prevent duplicate CCD appeals

- src/main/java/uk/gov/hmcts/sscs/service/SubmitAppealService.java
- src/test/java/uk/gov/hmcts/sscs/service/SubmitAppealServiceTest.java
Fix to prevent CCD being touched a second time if the first call fails to create a case.
> [PREVIEW]Sscs 4122 tribunals api nulls

- src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java
When the start date is in a different daylight savings period to the calculated future date, the time parts of the two dates, expressed in UTC, should be different. Previously the test always expected the UTC parts to be the same.
> [PREVIEW]Fix test when two dates bridge daylight savings

- src/test/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilderTest.java
After the change in daylight savings this past weekend, a test was failing due to an "off by one hour" error.
> Fix daylight savings issue in test

- infrastructure/main.tf
- infrastructure/preview.tfvars
We don't use the old preview environment built by Terraform.
This PR removes the old (Terraform) preview environment in favour of AKS.
> Removed old preview env

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-4820
We bump the sscs-common library version to 0.142. This brings in the TYA surname search changes described in the above ticket.
```
[ ] Yes
[x] No
```
> Bump common lib to 0.144

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-5232
Bump common library version to allow searching for appointee surnames.
Once this has been tested, then the following PR can be merged to master and an 0.0.145 version created of sscs-common. Then, update this PR to point to that new version and merge.
https://github.com/hmcts/sscs-common/pull/105
```
[ ] Yes
[x] No
```
> Sscs 5232 tya surnames

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- infrastructure/main.tf
- src/main/resources/config/application.properties
- src/main/resources/config/bootstrap.yaml
kubernetes does not like dots in environment variables.
> SSCS-5495: replace dots and dashes with underscores in environment variables

- build.gradle
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CreateCaseInCcdTest.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java
- src/main/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdService.java
- src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
- src/test/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/controller/SyaControllerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
# SSCS-5105: User can't return to a draft appeal once submitted
Requires SSCS-5604 to be completed first. i.e. SYA requires to send the Authorisation header if it exists.
Also requires CCD xlsx [4.3.51] change and a [sscs-commons change](https://github.com/hmcts/sscs-common/pull/149)
> SSCS-5105: Archive Draft once submitted.

- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/TyaEndpointsIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java
- src/main/java/uk/gov/hmcts/reform/sscs/controller/TyaController.java
- src/main/java/uk/gov/hmcts/reform/sscs/exception/AppealNotFoundException.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/TribunalsService.java
- src/test/java/uk/gov/hmcts/reform/sscs/controller/TyaControllerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/TribunalsServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/util/SerializeJsonMessageManager.java
- src/test/resources/tya/appealReceived-caseId.json
There used to be one that loaded them by TYA number but we many not have that for MYA.
```
[ ] Yes
[X] No
```
> Add an endpoint to load cases for MYA by case id

- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java
- src/main/resources/config/application.properties
The tribunals api in master is broken because when you submit your appeal, the state of the case is dependant of a flag `sendToDwp`. 
When switched on the status is `validAppeal` otherwise it’s `appealCreated`.
> fix tests on master

- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/TyaEndpointsIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/TribunalsService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/TribunalsServiceTest.java
Currently when navigating to the TYA web page as a representative or appointee, the links on the page result in either 404s or directs you to the TYA for the appellant. This issue seems to be a result of the links being rendered on the page with the appellant’s TYA number added at the end, whereas it should be the relevant TYA number added (representative’s if the rep’s was initially used or appointee’s if the appointee’s was used).
The reason for 404s is if there is no appellant subscription and therefore TYA number seen against the case, as is the case for appointee only cases.
Steps to reproduce
Find a case that has a representative or appointee subscription
Navigate to the TYA page for that user
Enter in the appropriate surname
Click on any of the links seen once in the TYA page …
> SSCS-5374 - TYA web page – Reps and Appointee – Links

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/InterlocServiceHandlerTest.java
rather than setting the interlocReviewState to null set it to "none"
as it doesn't look like the events can handle null.
https://tools.hmcts.net/jira/browse/SSCS-5812
```
[ ] Yes
[X] No
```
> SSCS-5812 Update interlocReviewState Field

- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java
Fix the functional SYA tests.
This _probably_ changed because we’ve taken the service bus away, and hence the asynchronous behaviour. We now have to wait for all the http request calls to complete. In any case at the moment the tests are wrong for what we have in production at the moment.
> fix functional tests

- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandlerTest.java
- src/test/resources/callback/judgeDecisionAppealToProceedEventCallback.json
- src/test/resources/callback/tcwDecisionAppealToProceedEventCallback.json
When you move a case out of interloc you need to attach a interloc
decision document. CCD does not enforce this so adding a presubmit
callback to check one has been set. We also need to make sure the doc is
a PDF so check this as well.
https://tools.hmcts.net/jira/browse/SSCS-6104
```
[ ] Yes
[X] No
```
> SSCS-6104 Validate Interloc Decision doc

- build.gradle
- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/event/CcdCallbackEndpointIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/ActionFurtherEvidenceDropdownHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/HandleEvidenceEventHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/HandleEvidenceEventHandlerTest.java
- src/test/resources/callback/actionFurtherEvidenceCallback.json
When running "Action Further Evidence" event, don't create a Document when the scannedDocument.document_type is "Coversheet".
JIRA: https://tools.hmcts.net/jira/browse/SSCS-6181
> SSCS-6181 - Don't create a Document when the scannedDocument.document_type is "Coversheet"

- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CcdCallbackEndpointIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/HandleEvidenceEventHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionfurtherevidence/HandleEvidenceEventHandlerTest.java
When running "Action Further Evidence" event, don't create a Document when the scannedDocument.document_type is "Coversheet".
The evidenceHandled should be set to “Yes if there are no errors.
if we remove the Scanned Documents, this must be set to "Yes", otherwise the case is in an incomplete state
If Scanned Document on case, evidenceHandled = "No"
if Scanned Documents were on case, but we remove them , then evidenceHandled = "Yes"
> SSCS-6181 - Set Evidence Handled to "Yes" when there are no errors.

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ValidateInterlocDecisionDocumentHandlerTest.java
When CCD calls the aboutToSubmit endpoint to validate interloc decision
documents it set the file name, date added and file type but not the
link. Therefore have to check the for absence of the link to determine
an interloc decision document has not beens et.
https://github.com/hmcts/sscs-cor-frontend/pull/367
```
[ ] Yes
[X] No
```
> SSCS-6104 Validate interloc document

- charts/sscs-tribunals-api/Chart.yaml
- charts/sscs-tribunals-api/requirements.yaml
- charts/sscs-tribunals-api/values.aat.template.yaml
- charts/sscs-tribunals-api/values.preview.template.yaml
- charts/sscs-tribunals-api/values.yaml
- src/main/resources/config/bootstrap.yaml
CHG0034613
Email to / email from configuration was missing in production causing defaults to be taken, this sets it up so that it's correctly pulled from vault.
I've updated chart-java to allow for templating of env variables, to reduce a lot of duplication
and moved non secret values to env vars to make debugging easier
```
[ ] Yes
[ ] No
```
> Add email_to / email_from + simplification

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandlerTest.java
Given a user runs the event "Ready to List"
When the event has completed
And the field "Created in GAPS from" is set to "Valid Appeal"
Then an error message will be displayed saying "Case already created in GAPS at Valid Appeal"
Then an email will NOT be sent to the GAPS Robot with a JSON file attached
> SSCS-6381 - Ready To List Event

- build.gradle
Because it wasn't in the data model
> SSCS-6699 - DWP response cleared

- build.gradle
- dependency-check-suppressions.xml
CVE-2019-16942, CVE-2019-16943 cannot be fixed as yet as we cannot upgrade jackson-databind further.
> suppress vulnerability

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7498
* Ensuring date validation fails for start and end date the same
* Changing syntax of error message to make the date requirement more specific
```
[ ] Yes
[ x] No
```
> SSCS-7498 Ensuring date validation fails for start and end date the same

- build.gradle
Fix for when docmosis errors and cannot convert files.
Associated PR https://github.com/hmcts/sscs-pdf-email-common/pull/267
> SSCS-7560 - docmosis error fix

- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/FinalDecisionIssuedForPreviewIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/ComparedRate.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/DirectionOrDecisionIssuedTemplateBody.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DecisionNoticeOutcomeServiceTest.java
- src/test/resources/callback/finalDecisionIssuedForPreview.json
https://tools.hmcts.net/jira/browse/SSCS-7554
Moving outcome calculation logic into shared DecisionNoticeOutcomeService.  Replacing Judge Name Placeholder with call to idam service for current user full name.
Adding is_allowed and is_set_aside flags to DirectionOrDecisionIssuedTemplateBody and setting based on outcome.  
Adding date_of_decision flag to DirectionOrDecisionIssuedTemplateBody and setting from casedata.
Adding key and getByKey method to ComparedRate
```
[ ] Yes
[ x] No
```
> SSCS-7554 Decision Notice Section 1

- build.gradle
- charts/sscs-tribunals-api/Chart.yaml
- charts/sscs-tribunals-api/values.yaml
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToStartHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/editbundle/EditBundleAboutToStartHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceRequestExecutor.java
- src/main/resources/config/application.properties
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToStartHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/directionissued/DirectionIssuedAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/editbundle/EditBundleAboutToStartTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/ServiceRequestExecutorTest.java
At the moment we are getting exceptions when users are doing the directionIssued event and they have selected “appealToProcceed” for the directionTypeDl, when the event is submitted this, then makes a call for the “appealToProceed” event to trigger. 
The exception occurs when the event is submitted and there is some data which causes the bulk scan validation to fail, all of which happens asynchronously, so the user is unaware that their case hasn’t progressed.
As part of the investigation into the issue that was seen against SSCS-7695, we want to hit the bulk scan OCR validation end point during the about to submit callback for the direction issued event, if they have selected the “appeal to proceed” direction type, if the validation were to then fail, then the error should be displayed …
> SSCS-7730 - CCD UI – Have directionIssued validate prior to submitting the event

- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java
- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToSubmitHandlerTest.java
- src/test/resources/callback/adjournCaseValidSubmissionWithNullGeneratedDate.json
- src/test/resources/callback/adjournCaseValidSubmissionWithSetGeneratedDate.json
- src/test/resources/callback/writeFinalDecisionDescriptorNullGeneratedDate.json
- src/test/resources/callback/writeFinalDecisionDescriptorSetGeneratedDate.json
https://tools.hmcts.net/jira/browse/SSCS-7854
*   Adding workaround for RDM-8200 to set the generated dates on the AboutToSubmit handlers.  Due to the generated dates being a hidden field, these values which are already set are being nulled out.   This is a workaround for that issue
```
[ ] Yes
[x] No
```
> SSCS-7854 Adding workaround for RDM-8200 to set the generated dates on the AboutToSubmit handlers

- dependency-check-suppressions.xml
suppress CVE-2020-15824 for a month until v1.4.0 kotlin-stdlib is released.
See also: https://github.com/square/okhttp/issues/6219
> suppress CVE-2020-15824 for a month until v1.4.0 kotlin-stdlib is released

- src/main/java/uk/gov/hmcts/reform/sscs/pdf/PdfACompliance.java
- src/main/java/uk/gov/hmcts/reform/sscs/pdf/PdfWatermarker.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/SscsPdfService.java
- src/main/java/uk/gov/hmcts/reform/sscs/thirdparty/pdfservice/InputStreamWrapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/thirdparty/pdfservice/ResourceManager.java
> Introducing InputStreamWrapper to safeClose an input stream automatically from try-with-resources-statements

- src/main/java/uk/gov/hmcts/reform/sscs/service/admin/RestoreCasesService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/admin/RestoreCasesServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8126
There was defensive code to check the case data state matched the case details state.  This was incorrect and has now been removed.
```
[ ] Yes
[x] No
```
> SSCS-8126 Ignoring case data state, only using state set on case details

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionMidEventValidationHandlerTest.java
[SSCS - 8112](https://tools.hmcts.net/jira/browse/SSCS-8112) - Activities are Optional depending on the award type
If no award is selected on both daily living & mobility the judge should not have to select activities on the Select activities - Write final decision page.
Activities should be optional
If it is not "No award" then user should be presented with an error message (At least one activity must be selected unless there is no award)
> SSCS - 8112 - Activities are Optional depending on the award type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8218
https://tools.hmcts.net/jira/browse/SSCS-8210
Adding validation to the action further evidence event so that:
* A warning message is displayed if either appellant or joint party have confidentiality granted.
* Confidentiality requests made when there is no joint party on the case cannot proceed and an error will be displayed.  
```
[ ] Yes
[x] No
```
> Sscs 8210 sscs 8218 action further evidence validation revised

- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/CitizenLoginTest.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/EvidenceUploadTest.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SscsMyaBackendRequests.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/mya/SubscriptionTest.java
SSCS-8317 - Add functional tests for MYA
- PUT: /api/citizen/cases/{caseId}/log 
- DELETE: /api/continuous-online-hearings/{identifier}/evidence/{evidenceId}
- POST: /appeals/{appealNumber}/subscriptions/{subscriptionId} 
- DELETE: /appeals/{id}/subscriptions/{subscriptionId}
> SSCS-8317 - Add functional tests for MYA

- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CcdMidEventControllerFunctionalTest.java
Test randomly fails with the following error:
> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> fix random failing test

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/DescriptorTable.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionPreviewDecisionServiceTestBase.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario4Test.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario6Test.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario9Test.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/pip/PipWriteFinalDecisionPreviewDecisionServiceTest.java
./ccd compose up -d ccd-definition-store-api
* Removing unnecessary award type validation for ESA.
* Changing existing descriptor logic to be schedule2 specific, and adding schedule3 descriptor logic
* Changing hidePointsColumn to hideAnswerColumns in DescriptorTable, and changing scenario tests accordingly
* Only validating now if generating notice, but validating for all other cases including non-wca appeals
* Fixing and unignoring two validation handler tests for generated date
* Merging in changes from the "approved scenario" PR including further unit tests.
```
[ ] Yes
[x] No
```
> SSCS-7578 Misc fixes

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/docassembly/WriteFinalDecisionTemplateContent.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario1Test.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario7Test.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario8Test.java
* In scenarios where schedule 2 activities were involved, it is valid to select no activities.  For this case we need to ensure that document can still be previewed.
```
[ ] Yes
[x] No
```
> SSCS-7578 Fixing NPE when no schedule 2 activities selected and adding tests

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaAllowedOrRefusedCondition.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesCondition.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaPointsRegulationsAndSchedule3ActivitiesConditionTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario2Test.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario3Test.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario4Test.java
https://tools.hmcts.net/jira/browse/SSCS-8425
Supports the scenario where schedule 2 sections and regulation 29 pages are not displayed for support group only ( ccd changes to be done separately) - for these scenario the schedule 2 questions will be null and regulation 29 unset.
This applies to Scenarios 2, 3, 4
```
[ ] Yes
[x] No
```
> SSCS-8425 Changes to support regulation 29 and schedule 2 sections not populated for support group only

- build.gradle
Change gradle repositories so that libs will be picked up from local first and then maven central.
Similar to https://github.com/hmcts/sscs-pdf-email-common/pull/457
`https://repo.spring.io/libs-milestone/` now requires authentication, so presumably, will never work if libraries need to be pulled from there
> Change gradle repositories so that libs will be picked up from local first then maven central

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionMidEventValidationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaWriteFinalDecisionPreviewDecisionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenario1Test.java
https://tools.hmcts.net/jira/browse/SSCS-8426
* Ensuring that we don't add Schedule2 descriptors to the template if no points were scored
* Ensuring that the validation mid event callback checks whether schedule3 activities are submitted if the flag to indicate they apply has been checked
```
[ ] Yes
[x] No
```
> SSCS-8426 Misc bug fixes

- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/EsaDecisionNoticeFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/EsaTemplateContent.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/esa/scenarios/EsaScenarioHearingTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8426
Fixing hearing type paragraph formatting - splitting into 2 paragraphs where necessary. Removing newlines from content output to the template
```
[ ] Yes
[x] No
```
> SSCS-8426 Fixing hearing type paragraph formatting

- dependency-check-suppressions.xml
CVE-2020-15824 Supressing CVE-2020-15824 until 31 Jan due to suspected false positive
```
[ ] Yes
[x] No
```
> CVE-2020-15824 suppression

- build.gradle
Fix for CVE-2020-17527-fix -  upgrade tomcat to 9.0.40
```
[ ] Yes
[x] No
```
> CVE-2020-17527 fix

- build.gradle
- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/UcDecisionNoticeOutcomeService.java
- src/test/resources/callback/writeFinalDecisionDescriptorESANonWCA.json
- src/test/resources/callback/writeFinalDecisionDescriptorUCNonLcwa.json
https://tools.hmcts.net/jira/browse/SSCS-8466
* Fixing bug where if non wca/lcwa route is selected,  but points-questions have previously been answered before selecting the non-wca/lcwa route and the points >=15,  the DN couldn't be previewed.   This was because the points were retained despite switching the route,  and no matching wca/lwca condition was found.
* Resolved this by clearing the points-questions before preview if non-wca/lcwa route 
```
[ ] Yes
[x] No
```
> Sscs 8466 non wca lwca existing points bugfix2

- build.gradle
- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/WriteFinalDecisionIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/EsaDecisionNoticeOutcomeService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/UcDecisionNoticeOutcomeService.java
- src/test/resources/callback/writeFinalDecisionDescriptorESANonWCA.json
- src/test/resources/callback/writeFinalDecisionDescriptorUCNonLcwa.json
https://tools.hmcts.net/jira/browse/SSCS-8466
* Fixing bug where if non wca/lcwa route is selected,  but points-questions have previously been answered before selecting the non-wca/lcwa route and the points >=15,  the DN couldn't be previewed.   This was because the points were retained despite switching the route,  and no matching wca/lwca condition was found.
* Resolved this by clearing the points-questions before preview if non-wca/lcwa route 
```
[ ] Yes
[x] No
```
> Sscs 8466 non wca/lcwa existing points bugfix

- build.gradle
Upgrade org.codehaus.groovy for CVE-2020-17521
> Upgrade org.codehaus.groovy for CVE-2020-17521

- .gitignore
Ignore git.properties file
The git.properties file will get auto generated when we compile the tribunal-api
It adds extra information to display git version on health endpoint
> Ignore git properties file

- src/main/java/uk/gov/hmcts/reform/sscs/service/SscsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/SscsPdfServiceTest.java
SSCS-8794 - Welsh cases - "Date appeal submitted" field is not populated with date value in generated SSCS1 Pdf letter
The appeal date submitted now appears in the SSCS1 Pdf
> SSCS-8794 - SSCS1 Pdf letter for welsh date appeal submitted

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploaddocuments/UploadDocumentFurtherEvidenceAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9293
When only an AV document was uploaded, an error was shown saying 'Your PDF Document is not readable.'. The method to check if the PDF is valid was always returning 'UNKNOWN' status for any mp3 or mp4. The unit test that existed passed because it also had a PDF in the test data, hence a false positive. Have added a test to cover the scenario for when only an mp3 or mp4 is uploaded with no pdf, and updated the code with the fix.
> SSCS-9293 Fix AV bug in upload fe event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/generatecoversheet/GenerateCoversheetAboutToStartHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/evidence/EvidenceUploadService.java
SSCS-9331 - Address fortify backend issues
https://emea.fortify.com/Releases/53243/Issues?t=-5102
- The method handle() in GenerateCoversheetAboutToStartHandler.java can crash the program by dereferencing a null-pointer on line 67.The program can potentially dereference a null-pointer, thereby causing a null-pointer exception.
- The call to endsWith() on line 335 causes portability problems because it has different locales which may lead to unexpected output. This may also circumvent custom validation routines.Unexpected portability problems can be found when the locale is not specified.
- The call to endsWith() on line 335 causes portability problems because it has different locales which may lead to unexpected output. This may also circumvent custom validation routines.Unexpected …
> SSCS-9331 - Address fortify backend issues

- charts/sscs-tribunals-api/Chart.yaml
- charts/sscs-tribunals-api/values.preview.template.yaml
- charts/sscs-tribunals-api/values.yaml
stop creating CCD containers in staging
There is no need to create the ccd staging containers
```
sscs-tribunals-api-staging-ccd-admin-web-5b8b44d98f-zm4kf         0/1     ContainerCreating   0          23m
sscs-tribunals-api-staging-ccd-data-store-api-7fdd6d4bdf-w2hb7    0/1     ContainerCreating   0          23m
sscs-tribunals-api-staging-ccd-definition-store-78c5ccc7-f5q86    0/1     ContainerCreating   0          23m
sscs-tribunals-api-staging-ccd-user-profile-api-68b6fd95679xbpq   0/1     ContainerCreating   0          23m
sscs-tribunals-api-staging-java-7c899d9fd7-bnjcn                  1/1     Running             0          23m
sscs-tribunals-api-staging-postgresql-0                           1/1     Running             0          23m
sscs-tribunals-api-staging-s2s-75df9cf7d9-5978s …
```
> stop creating CCD containers in staging

- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AbstractEventIt.java
- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UploadFurtherEvidenceIt.java
We are missing integration tests for the 'Upload further evidence' event in Tribunals API. These should be added to cover the various combinations of options
At minimum it should cover the happy path scenario where an Audio document is uploaded with a provided file name.
> SSCS-9386 - Upload Further Evidence Integration Tests

- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/BaseHandler.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/PdfHelper.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/UploadDocument.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/createbundle/CreateBundleAboutToSubmitHandlerFunctionalTest.java
- src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitHelper.java
Currently we are not testing preview, since the event is being run on AAT, the callbacks in CCD are using AAT's version of tribunals.
When we tried to hit the about to submit endpoint on tribunals, it does not save any case information, and there will be no case bundles.
If we do use the label : pr-values:ccd in the PR, we would be correctly testing the preview endpoint. (But we haven't got it working properly yet)
> SSCS-8366 - Add missing functional test for Bundling service

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/ResponseEventsAboutToSubmit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/controller/CreateCaseControllerTest.java
# SSCS-9328 - Upload response fields shouldn't accept AV
DWP response, AT38, DWP evidence bundle, DWP edited response, DWP edited response, Appendix 12 fields should allow PDF's
> SSCS-9328 - Upload response fields shouldn't accept AV

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/IssueDocumentHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
SSCS-9680 - Process Audio/Video Evidence Event - Directions Notice Label
The new field directionNoticeContent is used in the Process Audio/Video evidence event and use in a similar manner to the field bodyContent.
> SSCS-9680 - Process Audio/Video Evidence Event - Directions Notice Label

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/pip/PipIssueFinalDecisionAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/uc/UcIssueFinalDecisionAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-10335
Fix to use callback.casedetailsbefore.state instead of SscsCaseData.state in determining condition for hearings cancel message broadcast
```
[ ] Yes
[x] No
```
> Feat/sscs 10335 10328 - Further fix

- build.gradle
To fix CVE-2022-42252
```
[ ] Yes
[ x ] No
```
> bumps apache tomcat to 9.0.68

- Dockerfile
- src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/AdjournCaseIt.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-11656
Steps to follow:
Given an adjournment notice has been completed on the case
And the next hearing date was set to "First available date"
And different venue with same rpc as adjourned  was selected for the new hearing in the adjournment notice
When the new hearing is requested
Then the earliest hearing date is set to the 14 days after the adjournment notice issue date
Expected Results:
if the first hearing of the case is "Oral" and write adjournment has been performed on the case. The hearings tab is not loading. However, if the first hearing of the case is "paper" it is fine
https://manage-case-hearings-int.demo.platform.hmcts.net/cases/case-details/1682588875218296#Summary
Actual Results:
The hearings Tab is not loading 
Note: once the …
> SSCS-11656 - Fix Hearings Tab When First Hearing is Oral On Case

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerMainTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTestBase.java
https://tools.hmcts.net/jira/browse/SSCS-12005
An issue has been found during UAT whereby the standard time slot is not generating the duration expected by the business. This is because there are multiple ways that this should be calculated depending on the type of case. The system currently calculates this value based on the reference data for each case type however for some cases this value is set to Null as a Judge must define the duration so currently this would then set a default time of 60 mins which is incorrect. 
For cases where the value is NULL the business would like us to use the same duration that was set for the previous hearing as these would have been all been set by the Judge. 
However, rather than having 2 different methods the business would prefer a change to the …
> SSCS-12005 - Tribunals changes for setting of adjournment duration standard timeslot

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addnote/AddNoteAboutToSubmitHandler.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/addnote/AddNoteAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-554
- EXUI seems to be loosing value for label in dynamic list. As a result it would be good to rely on code and then get the label value from enum rather than relying on the dynamic list as it fails with null pointer exception.
`
"selectWhoReviewsCase": {
"value": {
"code": "reviewByJudge",
"label": null
},
"list_items": null
},
`
> Derive who review case label value using enum rather than dynamic list

- build.gradle
- charts/sscs-tribunals-api/Chart.yaml
- charts/sscs-tribunals-api/values.yaml
- src/functionalTest/resources/config/application_functional.properties
- src/main/resources/config/application.properties
https://tools.hmcts.net/jira/browse/SSCSCI-579
Add elinks feature flag to each env
> SSCSCI-579 - Elinks feature toggling

- charts/sscs-tribunals-api/values.ccd.preview.template.yaml
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToSubmitHandler.java
- src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-84
Ensuring the postponement request is only stored in the documents tab once (instead of twice) and that this request is always included in bundles
> SSCSCI-84 - Postponement doc appears twice V2

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-758
CVE-2023-44487
io.netty packages were already added as a dependency set for version 4.1.95.Final as a CVE fix before, recommendation was to upgrade them to version 4.1.100.Final or above. **Removed the dependency set** because the org.springframework.boot:2.7.18 patch also fixes this CVE, it uses version 4.1.101.Final.
CVE-2023-44487, CVE-2023-42794, CVE-2023-42795, CVE-2023-45648, CVE-2023-46589
org.apache.tomcat.embed:tomcat-embed-core and tomcat-embed-websocket
Recommendation by CVE-2023-46589 was to upgrade to 9.0.83, so **updated the direct dependency** to latest available patch (9.0.86).
CVE-2023-35116
com.fasterxml.jackson.core:jackson-databind:2.14.3
Recommendation was to upgrade to 2.16.0 but patch broke the build with error …
> Dependency patches

- build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-769
- Updated sscs-common to 5.3.4
- Removed dependency of org.apache.commons:commons-compress:1.26.0 (CVE-2024-25710) because that was coming from sscs-common.
> Update sscs-common to 5.3.4

- charts/sscs-tribunals-api/values.ccd.preview.template.yaml
[### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SSCSSI-151
-  As ccd definition is out of date with the code calls to updateCaseV2 fails with error `Case data validation failed: The following list of fields are in an invalid state: [workBasketHearingDateIssued]` and this exception is masked by IllegalArgumentException so the only way to see this exception is to start ccd in debug mode.
- Also update tya image as it uses incorrect PR image.
> Use latest image of tya notif and ccd definition

- charts/sscs-tribunals-api/Chart.yaml
- charts/sscs-tribunals-api/values.yaml
- src/main/java/uk/gov/hmcts/reform/sscs/evidenceshare/callback/handlers/AppealReceivedHandler.java
- src/main/resources/config/application.properties
- src/test/java/uk/gov/hmcts/reform/sscs/evidenceshare/callback/handlers/AppealReceivedHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCSSI-227
- This change uses trigger event v2 which does not uses callback case data to overwrite case data in DB.
-  This change impact below submitted events
```
EventType.VALID_APPEAL_CREATED
EventType.DRAFT_TO_VALID_APPEAL_CREATED
EventType.VALID_APPEAL
EventType.INTERLOC_VALID_APPEAL
CaseData().getCreatedInGapsFrom() is READY_TO_LIST
```
> Update appeal handler to use trigger event v2 instead of overwriting data from submitted callback

- Jenkinsfile_CNP
- charts/sscs-tribunals-api/values.ccd.preview.template.yaml
- https://tools.hmcts.net/jira/browse/SSCSCI-855
- remove default from env var evaluation in helm chart, because it's invalid syntax
- set the env var value in Jenkins, which is reading it from https://portal.azure.com/#@HMCTS.NET/asset/Microsoft_Azure_KeyVault/Secret/https://sscs-aat.vault.azure.net/secrets/preview-shared-db-password
> SSCSCI-855: remove default from chart var, set in jenkins

- src/main/java/uk/gov/hmcts/reform/sscs/service/servicebus/TopicConsumer.java
https://tools.hmcts.net/jira/browse/SSCSSI-352
Current logging without attempt is misleading if its the message within custom retry or queue retry.
Also, stack trace is not printed for other errors `
Statcktrace is jdk.internal.reflect.GeneratedMethodAccessor1619.invoke(Unknown Source) `
> SSCSSI-352 Fix logging in topicconsumer

- src/main/java/uk/gov/hmcts/reform/sscs/config/MessagingConfig.java
- src/main/resources/config/application.properties
Reverts hmcts/sscs-tribunals-case-api#3928
> "SSCSSI-352 | Fix prefetching issue with service bus topic message listeners"

- src/main/resources/config/application.yaml
https://tools.hmcts.net/jira/browse/SSCSSI-391
Currently, there is a conflict when spring tries to auto unbox the env var and it clashes with envidence. config.
Proved on demo that it's the cause of issue.
> Change environment var to avoid conflict

- Jenkinsfile_CNP
- definitions/test/e2e/write-and-issue-final-decision.spec.ts
- definitions/test/package.json
Allow selection of UI test suites by adding a label `test-suite:suiteName` to PRs
> Add support for test UI suites

- lib/applicationinsights.json
Currently, we nearly send 900k requests for /health on just AAT which are of no purpose.
> Add sampling for health requests

- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/handlers/AdminAppealWithdrawnNotificationsTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/EvidenceReceivedFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/JointPartyFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/NotificationsFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/OtherPartyFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/WelshNotificationsFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/sya/notifications/WithRepresentativePersonalisationTest.java
Reverts hmcts/sscs-tribunals-case-api#4133
> Revert "Disable functional tests as notifications to unblock rollback deployment"

- Jenkinsfile_CNP
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/tyanotifications/handlers/AdminAppealWithdrawnNotificationsTest.java
- Currently these tests are very flaky because we are waiting for correspondence pdf to be attached on the case. 
- This process is async, we poll the pdf from gov notify in an async process and attach it to the case. 
- This can take up a maximum of 10-15 minutes as discussed with Gov Notify before. 
- Since, we didn't want to remove the capability of testing the pdf attaching process, I am just limiting to one test while other 2 just confirm that letter has been sent to gov notify. 
- Also increased the timeout the test to 10 minutes. Though its a bit too much, its betetr than rerunning whole pipeline.
- An example case where i saw that the test failed, but pdf eventually got attached after ~7 mins.
- Timings of the pdf names are misleading, its the time when notification is sent to Gov …
> Change FTs to fetch correspondence for only 1 test

- definitions/benefit/sheets/CaseEventToFields/CaseEventToFields-nonprod.json
- definitions/benefit/sheets/CaseEventToFields/CaseEventToFields.json
See [SSCSCI-1347 ](https://tools.hmcts.net/jira/browse/SSCSCI-1347 )
> SSCSCI-1347 adding isFqpmRequired behind benefit type

- .github/workflows/ccd-diff.yaml
- definitions/benefit/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
- definitions/benefit/sheets/CaseEvent/CaseEvent.json
See [SSCSCI-1561](https://tools.hmcts.net/jira/browse/SSCSCI-1561)
- Changed caseOutcomeMigration event access to read only for anyone but `systemupdate` to hide it in Next Step
- Updated GitHub action to avoid reposting CCD diff report 
> u.g.h.r.m.service.CaseOutcomeMigrationServiceImpl Completed hearing found for case id 1736937034340606 with hearing id 2030031053
> u.g.h.r.m.service.CaseOutcomeMigrationServiceImpl case outcome found with value 9 and set to null for case id 1736937034340606
> u.g.h.r.m.service.CaseOutcomeMigrationServiceImpl did Po Attend found with value No and set to null for case id 1736937034340606
> u.g.h.r.m.service.CaseOutcomeMigrationServiceImpl Completed migration for case outcome migration. Case id: 1736937034340606
> …
> SSCSCI-1561: hide caseOutcomeMigration event

- charts/sscs-tribunals-api/Chart.yaml
Reverts hmcts/sscs-tribunals-case-api#4441
> Revert "Update repo due to a change in the way bitnami Helm charts are consumed"

- src/main/java/uk/gov/hmcts/reform/sscs/config/HighLevelDataSetupApp.java
- We have noticed that some service teams using WA have a CCD HighLevelDataSetupApp file which is configuring the WA system user role with a security classification of PUBLIC . 
- However this should actually be set to RESTRICTED since this system user ought to be able to access all Cases.  Since this runs in production this will mean that any Task initiations related to a restricted case will fail.
- Please can we ask all these service teams (sscs, prl, civil, civil general apps, sptribs) to urgently update the security classification to RESTRICTED to prevent any failures in the above scenario.
> Update wa system user classification to RESTRICTED
